import type { AdminActor } from '../../common/actors';
import { buildAdminAuditData } from '../../common/audit/admin-audit.builder';
import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, RiskAlertSeverity, RiskAlertType, WalletLedgerDirection } from '@prisma/client';
import { randomBytes } from 'crypto';
import { PrismaService } from '../../database/prisma.service';
import { AdminLedgerMutationService } from '../wallet/admin-ledger-mutation.service';

type RequestMeta = { ipAddress?: string; userAgent?: string };
type LedgerDryRunInput = { userId?: string; amount?: unknown; direction?: unknown; referenceType?: unknown; referenceId?: unknown; note?: unknown; idempotencyKey?: unknown };
type AlertRule = { code: string; type: RiskAlertType; title: string; severity: RiskAlertSeverity; description: string; queryHint: string };
type SimulatorWebhookMode = 'success' | 'failed' | 'timeout' | 'mismatch' | 'duplicate' | 'invalid_signature';

const REAL_LEDGER_MUTATION_ENABLED = process.env.REAL_LEDGER_MUTATION_ENABLED === 'true';
const WEBHOOK_EVENT_TYPES = ['simulator.transfer.completed', 'BET_SETTLED', 'WIN', 'ROLLBACK'] as const;
const ALERT_RULES: AlertRule[] = [
  { code: 'GAME_TRANSFER_FAILED', type: 'WALLET_LEDGER_MISMATCH', title: 'Game transfer failed', severity: 'HIGH', description: 'Dry-run or real game transfer has failed.', queryHint: 'gameTransfer.status = FAILED' },
  { code: 'WEBHOOK_INVALID_SIGNATURE', type: 'WALLET_LEDGER_MISMATCH', title: 'Webhook invalid signature', severity: 'CRITICAL', description: 'Provider webhook signature failed.', queryHint: 'webhookLog.signatureValid = false' },
  { code: 'WEBHOOK_DUPLICATE_SPIKE', type: 'WALLET_LEDGER_MISMATCH', title: 'Duplicate webhook spike', severity: 'MEDIUM', description: 'Duplicate provider webhooks detected.', queryHint: 'webhookLog.status = DUPLICATE' },
  { code: 'RECONCILIATION_MISMATCH', type: 'WALLET_LEDGER_MISMATCH', title: 'Reconciliation mismatch', severity: 'CRITICAL', description: 'Provider wallet snapshot is MISMATCH or UNKNOWN.', queryHint: 'providerWalletSnapshot.status IN (MISMATCH, UNKNOWN)' },
  { code: 'PROVIDER_DEGRADED', type: 'WALLET_LEDGER_MISMATCH', title: 'Provider health degraded', severity: 'HIGH', description: 'Provider is degraded or in maintenance.', queryHint: 'gameProvider.status IN (DEGRADED, MAINTENANCE)' },
  { code: 'REAL_MONEY_GATE_ENABLED', type: 'WALLET_LEDGER_MISMATCH', title: 'Real money gate enabled', severity: 'CRITICAL', description: 'Provider realMoneyEnabled gate is enabled.', queryHint: 'gameProvider.metadata.realMoneyEnabled = true' },
];

@Injectable()
export class MoneyOpsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly adminLedgerMutation: AdminLedgerMutationService,
  ) {}

  async financeControlCenter() {
    const [walletCount, ledgers, failedTransfers, pendingTransfers, mismatchSnapshots, webhookFailed, duplicateWebhooks, openRiskAlerts, recentLedgers, recentTransfers, recentSnapshots, recentAlerts] = await Promise.all([
      this.prisma.wallet.count(),
      this.prisma.walletLedger.findMany({ orderBy: { createdAt: 'desc' }, take: 1, select: { id: true } }),
      this.prisma.gameTransfer.count({ where: { status: 'FAILED' } }),
      this.prisma.gameTransfer.count({ where: { status: 'PENDING' } }),
      this.prisma.providerWalletSnapshot.count({ where: { status: { in: ['MISMATCH', 'UNKNOWN'] } } }),
      this.prisma.webhookLog.count({ where: { status: 'FAILED' } }),
      this.prisma.webhookLog.count({ where: { status: 'DUPLICATE' } }),
      this.prisma.riskAlert.count({ where: { status: { in: ['OPEN', 'REVIEWING'] } } }),
      this.prisma.walletLedger.findMany({ orderBy: { createdAt: 'desc' }, take: 10, include: { user: { select: { id: true, username: true, phone: true } } } }),
      this.prisma.gameTransfer.findMany({ orderBy: { createdAt: 'desc' }, take: 10, include: { provider: { select: { name: true, code: true } }, user: { select: { username: true, phone: true } } } }),
      this.prisma.providerWalletSnapshot.findMany({ orderBy: { checkedAt: 'desc' }, take: 10, include: { provider: { select: { name: true, code: true } }, user: { select: { username: true, phone: true } } } }),
      this.prisma.riskAlert.findMany({ where: { status: { in: ['OPEN', 'REVIEWING'] } }, orderBy: { createdAt: 'desc' }, take: 10 }),
    ]);
    return { summary: { walletCount, ledgerActivity: ledgers.length, failedTransfers, pendingTransfers, mismatchSnapshots, webhookFailed, duplicateWebhooks, openRiskAlerts }, queues: { failedTransfers, pendingTransfers, mismatchSnapshots, webhookFailed, duplicateWebhooks, openRiskAlerts }, recent: { ledgers: recentLedgers, transfers: recentTransfers, snapshots: recentSnapshots, alerts: recentAlerts }, realLedgerMutationEnabled: REAL_LEDGER_MUTATION_ENABLED };
  }

  async listLedger(query: { userId?: string; referenceType?: string; referenceId?: string; take?: string | number }) { const take = Math.min(Math.max(Number(query.take ?? 50), 1), 100); const where: Prisma.WalletLedgerWhereInput = {}; if (query.userId) where.userId = query.userId; if (query.referenceType) where.referenceType = query.referenceType; if (query.referenceId) where.referenceId = query.referenceId; const items = await this.prisma.walletLedger.findMany({ where, orderBy: { createdAt: 'desc' }, take, include: { user: { select: { id: true, username: true, phone: true } }, wallet: { select: { id: true, currency: true, balance: true, lockedBalance: true } } } }); return { items, total: items.length }; }
  simulateLedgerMutation(body: LedgerDryRunInput) { const parsed = this.parseLedgerInput(body); const balanceBefore = 1000; const balanceAfter = parsed.direction === 'CREDIT' ? balanceBefore + parsed.amount : balanceBefore - parsed.amount; const ok = balanceAfter >= 0; return { ok, dryRun: true, mutation: { ...parsed, amount: parsed.amount.toFixed(2), balanceBefore: balanceBefore.toFixed(2), balanceAfter: balanceAfter.toFixed(2) }, warning: ok ? null : 'Insufficient simulated balance' }; }
  async mutateLedger(actor: AdminActor, meta: RequestMeta, body: LedgerDryRunInput) { if (!REAL_LEDGER_MUTATION_ENABLED) throw new ForbiddenException('REAL_LEDGER_MUTATION_ENABLED is not enabled'); const parsed = this.parseLedgerInput(body); const item = await this.adminLedgerMutation.execute(actor, meta, { userId: parsed.userId, amount: parsed.amount.toFixed(2), direction: parsed.direction, referenceType: parsed.referenceType, referenceId: parsed.referenceId, idempotencyKey: parsed.idempotencyKey, note: parsed.note }); return { ok: true, item, realMutation: true }; }
  async writeAudit(actor: AdminActor, meta: RequestMeta, input: { action: string; module: string; targetId?: string; oldData?: unknown; newData?: unknown }) { const item = await this.prisma.adminAuditLog.create({ data: buildAdminAuditData({ adminUserId: actor.id, action: input.action, module: input.module, targetId: input.targetId, oldData: input.oldData, newData: input.newData, ipAddress: meta.ipAddress, userAgent: meta.userAgent }) }); return { ok: true, item }; }
  listAlertRules() { return { items: ALERT_RULES, dryRun: false }; }
  async scanAlertRules(actor: AdminActor, meta: RequestMeta) { const findings = (await Promise.all([this.findFailedTransfers(), this.findInvalidWebhooks(), this.findDuplicateWebhooks(), this.findMismatchSnapshots(), this.findDegradedProviders(), this.findRealMoneyEnabledProviders()])).flat(); const persisted = []; for (const finding of findings) persisted.push(await this.upsertRiskAlert(finding)); await this.writeAudit(actor, meta, { action: 'alert_rules.scan', module: 'money_ops', newData: { findings, persisted: persisted.length } }); return { findings, persisted, dryRun: false }; }
  async resolveRiskAlert(id: string, actor: AdminActor, meta: RequestMeta, note?: string) { const current = await this.prisma.riskAlert.findUnique({ where: { id } }); if (!current) throw new NotFoundException('Risk alert not found'); const item = await this.prisma.riskAlert.update({ where: { id }, data: { status: 'RESOLVED', resolvedAt: new Date(), metadata: this.mergeJson(current.metadata, { resolutionNote: note ?? null, resolvedBy: actor.id, resolvedAt: new Date().toISOString() }) } }); await this.writeAudit(actor, meta, { action: 'risk_alert.resolve', module: 'money_ops', targetId: id, oldData: current, newData: item }); return { ok: true, item }; }
  async dismissRiskAlert(id: string, actor: AdminActor, meta: RequestMeta, note?: string) { const current = await this.prisma.riskAlert.findUnique({ where: { id } }); if (!current) throw new NotFoundException('Risk alert not found'); const item = await this.prisma.riskAlert.update({ where: { id }, data: { status: 'DISMISSED', resolvedAt: new Date(), metadata: this.mergeJson(current.metadata, { dismissNote: note ?? null, dismissedBy: actor.id, dismissedAt: new Date().toISOString() }) } }); await this.writeAudit(actor, meta, { action: 'risk_alert.dismiss', module: 'money_ops', targetId: id, oldData: current, newData: item }); return { ok: true, item }; }

  simulatorScenarios() { return { scenarios: [{ code: 'launch_success', description: 'Fake provider returns launchUrl and session id.' }, { code: 'balance_success', description: 'Fake provider returns stable balance.' }, { code: 'balance_mismatch', description: 'Fake provider returns a balance mismatch.' }, { code: 'transfer_in_success', description: 'Fake provider accepts transfer in.' }, { code: 'transfer_out_success', description: 'Fake provider accepts transfer out.' }, { code: 'transfer_failed', description: 'Fake provider rejects transfer.' }, { code: 'timeout', description: 'Fake provider timeout/ambiguous response.' }, { code: 'duplicate_webhook', description: 'Fake provider sends the same idempotency key twice.' }, { code: 'invalid_signature', description: 'Fake provider sends invalid signature headers.' }, { code: 'webhook_rollback', description: 'Fake provider sends a rollback event.' }, { code: 'webhook_win', description: 'Fake provider sends a win event.' }, { code: 'webhook_bet_settled', description: 'Fake provider sends a bet settled event.' }], webhookPayloadExample: { eventType: 'simulator.transfer.completed', idempotencyKey: 'simulator-idempotency-key', providerTransactionId: 'simulator-tx-id' }, eventTypes: WEBHOOK_EVENT_TYPES, modes: ['success', 'failed', 'timeout', 'mismatch', 'duplicate', 'invalid_signature'] }; }
  simulatorHealth() { return { ok: true, providerCode: 'simulator-provider', status: 'ONLINE', latencyMs: 12, dryRun: true }; }
  simulatorLaunch(body: any) { const mode = this.simMode(body); if (mode === 'timeout') return this.simTimeout('LAUNCH_TIMEOUT'); if (mode === 'failed') return this.simFail('LAUNCH_FAILED'); const gameCode = String(body?.gameCode ?? 'sim-slot-001'); const sessionId = `sim_session_${Date.now()}_${randomBytes(3).toString('hex')}`; return { ok: true, providerCode: 'simulator-provider', launchUrl: `/provider-simulator/play?game=${encodeURIComponent(gameCode)}&session=${encodeURIComponent(sessionId)}`, providerSessionId: sessionId, expiresAt: new Date(Date.now() + 15 * 60 * 1000).toISOString(), rawRequest: body ?? null, dryRun: true, mode }; }
  simulatorBalance(body: any) { const mode = this.simMode(body); if (mode === 'timeout') return this.simTimeout('BALANCE_TIMEOUT'); const balance = mode === 'mismatch' ? '777.77' : '1000.00'; return { ok: true, providerCode: 'simulator-provider', userId: body?.userId ?? 'sim-user', balance, currency: body?.currency ?? 'THB', rawRequest: body ?? null, dryRun: true, mode }; }
  simulatorTransfer(body: any, type: 'TRANSFER_IN' | 'TRANSFER_OUT') { const mode = this.simMode(body); if (mode === 'timeout') return this.simTimeout(`${type}_TIMEOUT`); const amount = Number(body?.amount ?? 0); if (!Number.isFinite(amount) || amount <= 0) throw new BadRequestException('amount must be positive'); const idempotencyKey = String(body?.idempotencyKey ?? `sim_${type.toLowerCase()}_${Date.now()}`); if (mode === 'failed') return { ok: false, providerCode: 'simulator-provider', type, amount: amount.toFixed(2), currency: body?.currency ?? 'THB', idempotencyKey, errorCode: 'SIMULATED_TRANSFER_FAILED', errorMessage: 'Fake provider rejected transfer. No wallet mutation happened.', rawRequest: body ?? null, dryRun: true, mode }; return { ok: true, providerCode: 'simulator-provider', type, amount: amount.toFixed(2), currency: body?.currency ?? 'THB', idempotencyKey, providerTransactionId: `sim_tx_${randomBytes(5).toString('hex')}`, rawRequest: body ?? null, dryRun: true, mode }; }
  simulatorWebhook(body: any) { return this.buildSimulatorWebhookTest(body).primary; }
  async simulatorWebhookTest(body: any) { const result = this.buildSimulatorWebhookTest(body); const providerCode = String(body?.providerCode ?? 'simulator-provider'); const provider = await this.prisma.gameProvider.findUnique({ where: { code: providerCode }, select: { id: true, code: true, name: true } }); const shouldPersist = body?.persistLogs !== false; const logs = provider && shouldPersist ? await this.persistSimulatorWebhookLogs(provider.id, result.requests) : []; return { ...result, provider, logs, logWarning: provider ? null : `Provider ${providerCode} was not found; generated payloads only.`, persistedLogs: logs.length, noSettlement: true }; }
  simulatorTimeout() { return this.simTimeout('SIMULATED_TIMEOUT'); }
  securityHardeningChecklist() { return { items: ['Rate limit admin money operations', 'Rate limit provider webhook endpoints', 'Limit webhook request body size', 'Add provider IP allowlist before real settlement', 'Rotate provider credentials on schedule', 'Audit every gate/retry/review/resolve action', 'Keep realMoneyEnabled false until preflight passes', 'Test backup and restore before real wallet mutation'] }; }

  private buildSimulatorWebhookTest(body: any) { const mode = this.simMode(body) as SimulatorWebhookMode; const requestedEventType = String(body?.eventType ?? this.defaultWebhookEventType(mode)); const eventType = WEBHOOK_EVENT_TYPES.includes(requestedEventType as any) ? requestedEventType : 'simulator.transfer.completed'; const idempotencyKey = String(body?.idempotencyKey ?? (mode === 'duplicate' ? 'sim_duplicate_key' : `sim_webhook_${Date.now()}`)); const providerTransactionId = String(body?.providerTransactionId ?? `sim_tx_${randomBytes(5).toString('hex')}`); const payload = this.webhookPayload(eventType, idempotencyKey, providerTransactionId, body); const headers = { 'x-provider-signature': mode === 'invalid_signature' ? 'invalid-signature' : 'simulated-signature', 'x-provider-timestamp': String(Date.now()) }; const request = { headers, payload, expectedStatus: this.expectedWebhookStatus(mode), expectedSignatureValid: mode !== 'invalid_signature', noSettlement: true }; const duplicateRequest = mode === 'duplicate' ? { ...request, expectedStatus: 'DUPLICATE' as const, duplicateOf: idempotencyKey } : null; const requests = duplicateRequest ? [request, duplicateRequest] : [request]; return { ok: mode !== 'invalid_signature', providerCode: String(body?.providerCode ?? 'simulator-provider'), dryRun: true, mode, eventType, primary: { ok: mode !== 'invalid_signature', headers, payload, dryRun: true, mode, noSettlement: true }, requests, explanation: this.webhookModeExplanation(mode), supportedEventTypes: WEBHOOK_EVENT_TYPES }; }
  private async persistSimulatorWebhookLogs(providerId: string, requests: Array<{ payload: Record<string, unknown>; expectedStatus: string; expectedSignatureValid: boolean }>) { const items = []; for (const request of requests) { items.push(await this.prisma.webhookLog.create({ data: { providerId, eventType: String(request.payload.eventType ?? 'UNKNOWN'), status: request.expectedStatus as any, signatureValid: request.expectedSignatureValid, idempotencyKey: request.payload.idempotencyKey ? String(request.payload.idempotencyKey) : undefined, providerTransactionId: request.payload.providerTransactionId ? String(request.payload.providerTransactionId) : undefined, rawPayload: this.safeJson(request.payload), normalizedPayload: this.safeJson({ ...request.payload, simulatorTest: true, noSettlement: true }), responseStatus: request.expectedStatus === 'FAILED' ? 400 : 200, errorCode: request.expectedStatus === 'FAILED' ? 'SIMULATED_INVALID_SIGNATURE' : undefined, errorMessage: request.expectedStatus === 'FAILED' ? 'Simulated invalid signature. No settlement was performed.' : undefined, processedAt: new Date() } })); } return items; }
  private defaultWebhookEventType(mode: string) { if (mode === 'rollback') return 'ROLLBACK'; if (mode === 'win') return 'WIN'; if (mode === 'bet_settled') return 'BET_SETTLED'; return 'simulator.transfer.completed'; }
  private webhookPayload(eventType: string, idempotencyKey: string, providerTransactionId: string, body: any) { return { eventType, idempotencyKey, providerTransactionId, amount: String(body?.amount ?? '100.00'), currency: String(body?.currency ?? 'THB'), roundId: String(body?.roundId ?? `sim_round_${randomBytes(4).toString('hex')}`), userId: body?.userId ? String(body.userId) : undefined, gameCode: String(body?.gameCode ?? 'sim-slot-001'), occurredAt: new Date().toISOString(), metadata: { simulator: true, noSettlement: true, requestedMode: this.simMode(body) } }; }
  private expectedWebhookStatus(mode: string) { if (mode === 'invalid_signature') return 'FAILED'; if (mode === 'duplicate') return 'PROCESSED'; if (mode === 'failed') return 'FAILED'; return 'PROCESSED'; }
  private webhookModeExplanation(mode: string) { if (mode === 'duplicate') return 'Two generated requests share the same idempotencyKey; the second request is marked as DUPLICATE for log testing.'; if (mode === 'invalid_signature') return 'Generated request uses an invalid signature and is expected to fail without settlement.'; if (mode === 'failed') return 'Generated request is marked failed for webhook error UI testing.'; return 'Generated webhook payload is safe for UI/log testing and does not mutate wallets.'; }
  private parseLedgerInput(body: LedgerDryRunInput) { if (!body.userId || typeof body.userId !== 'string') throw new BadRequestException('userId is required'); const amount = Number(body.amount); if (!Number.isFinite(amount) || amount <= 0) throw new BadRequestException('amount must be positive'); const direction = body.direction === 'DEBIT' ? 'DEBIT' : body.direction === 'CREDIT' ? 'CREDIT' : null; if (!direction) throw new BadRequestException('direction must be CREDIT or DEBIT'); return { userId: body.userId, direction: direction as WalletLedgerDirection, amount, referenceType: String(body.referenceType ?? 'MANUAL_LEDGER'), referenceId: body.referenceId ? String(body.referenceId) : null, idempotencyKey: String(body.idempotencyKey ?? `ledger_${Date.now()}_${randomBytes(4).toString('hex')}`), note: body.note ? String(body.note) : null }; }
  private async findFailedTransfers() { const rule = this.rule('GAME_TRANSFER_FAILED'); const items = await this.prisma.gameTransfer.findMany({ where: { status: 'FAILED' }, take: 25, orderBy: { createdAt: 'desc' }, select: { id: true, errorMessage: true, userId: true, providerId: true } }); return items.map((item) => ({ rule, refType: 'GameTransfer', refId: item.id, memberId: item.userId, metadata: item })); }
  private async findInvalidWebhooks() { const rule = this.rule('WEBHOOK_INVALID_SIGNATURE'); const items = await this.prisma.webhookLog.findMany({ where: { signatureValid: false }, take: 25, orderBy: { createdAt: 'desc' }, select: { id: true, eventType: true, errorMessage: true, providerId: true } }); return items.map((item) => ({ rule, refType: 'WebhookLog', refId: item.id, memberId: null, metadata: item })); }
  private async findDuplicateWebhooks() { const rule = this.rule('WEBHOOK_DUPLICATE_SPIKE'); const items = await this.prisma.webhookLog.findMany({ where: { status: 'DUPLICATE' }, take: 25, orderBy: { createdAt: 'desc' }, select: { id: true, eventType: true, idempotencyKey: true, providerId: true } }); return items.map((item) => ({ rule, refType: 'WebhookLog', refId: item.id, memberId: null, metadata: item })); }
  private async findMismatchSnapshots() { const rule = this.rule('RECONCILIATION_MISMATCH'); const items = await this.prisma.providerWalletSnapshot.findMany({ where: { status: { in: ['MISMATCH', 'UNKNOWN'] } }, take: 25, orderBy: { checkedAt: 'desc' }, select: { id: true, status: true, userId: true, providerId: true, difference: true } }); return items.map((item) => ({ rule, refType: 'ProviderWalletSnapshot', refId: item.id, memberId: item.userId, metadata: item })); }
  private async findDegradedProviders() { const rule = this.rule('PROVIDER_DEGRADED'); const items = await this.prisma.gameProvider.findMany({ where: { status: { in: ['DEGRADED', 'MAINTENANCE'] } }, take: 25, orderBy: { updatedAt: 'desc' }, select: { id: true, name: true, code: true, status: true } }); return items.map((item) => ({ rule, refType: 'GameProvider', refId: item.id, memberId: null, metadata: item })); }
  private async findRealMoneyEnabledProviders() { const rule = this.rule('REAL_MONEY_GATE_ENABLED'); const items = await this.prisma.gameProvider.findMany({ take: 100, orderBy: { updatedAt: 'desc' }, select: { id: true, name: true, code: true, metadata: true } }); return items.filter((item) => this.objectJson(item.metadata).realMoneyEnabled === true).map((item) => ({ rule, refType: 'GameProvider', refId: item.id, memberId: null, metadata: item })); }
  private async upsertRiskAlert(input: { rule: AlertRule; refType: string; refId: string; memberId: string | null; metadata: unknown }) { const existing = await this.prisma.riskAlert.findFirst({ where: { refType: input.refType, refId: input.refId, type: input.rule.type, status: { in: ['OPEN', 'REVIEWING'] } } }); if (existing) return { ...existing, deduped: true }; const created = await this.prisma.riskAlert.create({ data: { type: input.rule.type, severity: input.rule.severity, status: 'OPEN', memberId: input.memberId ?? undefined, refType: input.refType, refId: input.refId, title: input.rule.title, description: input.rule.description, metadata: this.safeJson({ code: input.rule.code, source: 'money_ops.alert_rules.scan', payload: input.metadata }) } }); return { ...created, deduped: false }; }
  private rule(code: string) { const rule = ALERT_RULES.find((item) => item.code === code); if (!rule) throw new BadRequestException(`Unknown alert rule: ${code}`); return rule; }
  private simMode(body: any) { return String(body?.mode ?? body?.scenario ?? 'success').toLowerCase(); }
  private simFail(code: string) { return { ok: false, providerCode: 'simulator-provider', errorCode: code, errorMessage: 'Fake provider failure. No wallet mutation happened.', dryRun: true, mode: 'failed' }; }
  private simTimeout(code: string) { return { ok: false, providerCode: 'simulator-provider', errorCode: code, errorMessage: 'Fake provider timeout/ambiguous response. No wallet mutation happened.', dryRun: true, mode: 'timeout' }; }
  private objectJson(value: unknown) { return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
  private safeJson(value: unknown) { return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue; }
  private mergeJson(current: unknown, patch: Record<string, unknown>) { return this.safeJson({ ...this.objectJson(current), ...patch }); }
}
