'use client';

import { useMemo, useState } from 'react';
import { adminApiFetch } from '../../admin-api';
import { AdminBadge, AdminButton, AdminCard, AdminGrid, AdminNotice, AdminPage, AdminRow, AdminStack } from '../_components/admin-ui';

const presets = [
  { name: 'เดโม', code: 'demo-provider', mode: 'TRANSFER', risk: 'Safe', endpoints: ['LAUNCH', 'BALANCE', 'TRANSFER_IN', 'TRANSFER_OUT', 'WEBHOOK', 'HEALTH_CHECK'], credentials: ['API_KEY', 'WEBHOOK_SECRET'], gates: ['launchEnabled', 'transferEnabled', 'walletSyncEnabled'] },
  { name: 'จำลองระบบค่าย', code: 'simulator-provider', mode: 'TRANSFER', risk: 'Safe', endpoints: ['LAUNCH', 'BALANCE', 'TRANSFER_IN', 'TRANSFER_OUT', 'WEBHOOK', 'HEALTH_CHECK'], credentials: ['API_KEY', 'WEBHOOK_SECRET'], gates: ['launchEnabled', 'transferEnabled', 'walletSyncEnabled'] },
  { name: 'โยกเงินทั่วไป', code: 'generic-transfer', mode: 'TRANSFER', risk: 'Market', endpoints: ['LAUNCH', 'BALANCE', 'TRANSFER_IN', 'TRANSFER_OUT', 'GAME_LIST', 'WEBHOOK', 'HEALTH_CHECK'], credentials: ['API_KEY', 'SECRET_KEY', 'MERCHANT_ID', 'WEBHOOK_SECRET'], gates: ['launchEnabled', 'walletSyncEnabled'] },
  { name: 'Seamless ขั้นสูง', code: 'generic-seamless', mode: 'SEAMLESS', risk: 'Advanced', endpoints: ['LAUNCH', 'BALANCE', 'BET_HISTORY', 'WEBHOOK', 'HEALTH_CHECK'], credentials: ['API_KEY', 'SECRET_KEY', 'AGENT_ID', 'WEBHOOK_SECRET'], gates: ['launchEnabled', 'webhookSettlementEnabled'] },
  { name: 'ค่ายจริงแบบปรับเอง', code: 'real-provider', mode: 'HYBRID', risk: 'Danger', endpoints: ['LAUNCH', 'BALANCE', 'TRANSFER_IN', 'TRANSFER_OUT', 'GAME_LIST', 'BET_HISTORY', 'WEBHOOK', 'HEALTH_CHECK'], credentials: ['API_KEY', 'SECRET_KEY', 'MERCHANT_ID', 'AGENT_ID', 'WEBHOOK_SECRET'], gates: ['launchEnabled'] },
];
type Preset = typeof presets[number];

export default function ProviderPresetsPage() {
  const [message, setMessage] = useState('');
  const [working, setWorking] = useState(false);
  const [selected, setSelected] = useState<Preset>(presets[2]);
  const [form, setForm] = useState({ name: 'Generic Transfer UAT', code: 'generic-transfer-uat', baseUrl: 'https://provider.example.test/api', apiKey: '', secretKey: '', merchantId: '', agentId: '', webhookSecret: '', enabledEndpoints: presets[2].endpoints });
  const endpointPreview = useMemo(() => form.enabledEndpoints.map((type) => ({ type, url: `${form.baseUrl.replace(/\/+$/, '')}/${type.toLowerCase().replaceAll('_', '-')}` })), [form.baseUrl, form.enabledEndpoints]);
  const filledCredentials = useMemo(() => selected.credentials.filter((credential) => Boolean(credentialValue(credential, form))), [selected, form]);
  const missingCredentials = selected.credentials.filter((credential) => !filledCredentials.includes(credential));
  function choosePreset(preset: Preset) { setSelected(preset); setForm((current) => ({ ...current, name: `${preset.name} UAT`, code: `${preset.code}-uat`, enabledEndpoints: preset.endpoints })); setMessage(''); }
  function update(key: keyof typeof form, value: string | string[]) { setForm((current) => ({ ...current, [key]: value })); }
  function toggleEndpoint(endpoint: string) { setForm((current) => ({ ...current, enabledEndpoints: current.enabledEndpoints.includes(endpoint) ? current.enabledEndpoints.filter((item) => item !== endpoint) : [...current.enabledEndpoints, endpoint] })); }
  async function applyPreset() { if (!form.name.trim() || !form.code.trim() || !form.baseUrl.trim()) { setMessage('กรอกชื่อค่าย / รหัสค่าย / Base URL ให้ครบก่อน'); return; } if (form.enabledEndpoints.length === 0) { setMessage('ต้องเลือก URL API อย่างน้อย 1 รายการ'); return; } if (missingCredentials.length > 0 && !window.confirm(`ยังไม่ได้กรอก: ${missingCredentials.map(credentialLabel).join(', ')} ยืนยันสร้างไว้ก่อนใช่ไหม?`)) return; setWorking(true); setMessage('กำลังสร้างค่าย...'); const res = await adminApiFetch('/admin/provider-presets/apply', { method: 'POST', body: JSON.stringify({ presetCode: selected.code, name: form.name, code: form.code, baseUrl: form.baseUrl, enabledEndpoints: form.enabledEndpoints, endpointOverrides: endpointPreview, apiKey: form.apiKey, secretKey: form.secretKey, merchantId: form.merchantId, agentId: form.agentId, webhookSecret: form.webhookSecret, status: 'INACTIVE' }) }); const data = await res.json().catch(() => null); setWorking(false); if (!res.ok || !data?.ok) { setMessage(data?.message ?? 'สร้างค่ายไม่สำเร็จ'); return; } setMessage(`สร้างค่ายแล้ว: ${data.provider?.name ?? form.name}`); window.location.href = '/simple-game-settings'; }
  return <AdminPage eyebrow="ตั้งค่าค่ายเกม" title="แบบตั้งค่าค่าย" description="เลือกแบบเริ่มต้นแล้วแก้ชื่อค่าย, URL API และ API Key ก่อนสร้าง">
    <AdminNotice>ค่ายที่สร้างจะ “ปิดอยู่” ก่อนเสมอ จากนั้นไปทดสอบและเปิดใช้งานจากหน้าตั้งค่าง่าย</AdminNotice>{message && <AdminNotice>{message}</AdminNotice>}
    <AdminGrid>{presets.map((preset) => <AdminCard key={preset.code} title={preset.name} description={presetDescription(preset.code)} action={<AdminButton tone={selected.code === preset.code ? 'primary' : 'secondary'} onClick={() => choosePreset(preset)}>{selected.code === preset.code ? 'เลือกแล้ว' : 'เลือกแบบนี้'}</AdminButton>}><AdminRow><strong>ความเสี่ยง</strong><AdminBadge tone={riskTone(preset.risk)}>{riskLabel(preset.risk)}</AdminBadge></AdminRow><section style={blockStyle}><strong>URL API ที่ใช้</strong><div style={tagRowStyle}>{preset.endpoints.map((item) => <AdminBadge key={item} tone="neutral">{endpointLabel(item)}</AdminBadge>)}</div></section><section style={blockStyle}><strong>ค่าจากค่ายที่ต้องใช้</strong><div style={tagRowStyle}>{preset.credentials.map((item) => <AdminBadge key={item} tone="warning">{credentialLabel(item)}</AdminBadge>)}</div></section></AdminCard>)}</AdminGrid>
    <h2 style={sectionTitleStyle}>แก้ก่อนสร้าง: {selected.name}</h2><AdminGrid><AdminCard title="ข้อมูลค่าย" description="แก้ชื่อและ URL ก่อนสร้างจริง"><div style={formStyle}><label style={labelStyle}>ชื่อค่าย<input value={form.name} onChange={(event) => update('name', event.target.value)} style={inputStyle} /></label><label style={labelStyle}>รหัสค่าย<input value={form.code} onChange={(event) => update('code', event.target.value)} style={inputStyle} /></label><label style={labelStyle}>Base URL<input value={form.baseUrl} onChange={(event) => update('baseUrl', event.target.value)} style={inputStyle} /></label></div></AdminCard><AdminCard title="API Key / Secret" description="ระบบจะซ่อนค่าเหล่านี้ ไม่แสดงค่าจริงกลับหน้าเว็บ"><div style={formStyle}>{selected.credentials.includes('API_KEY') && <label style={labelStyle}>API Key<input value={form.apiKey} onChange={(event) => update('apiKey', event.target.value)} style={inputStyle} /></label>}{selected.credentials.includes('SECRET_KEY') && <label style={labelStyle}>Secret Key<input value={form.secretKey} onChange={(event) => update('secretKey', event.target.value)} style={inputStyle} /></label>}{selected.credentials.includes('MERCHANT_ID') && <label style={labelStyle}>Merchant ID<input value={form.merchantId} onChange={(event) => update('merchantId', event.target.value)} style={inputStyle} /></label>}{selected.credentials.includes('AGENT_ID') && <label style={labelStyle}>Agent ID<input value={form.agentId} onChange={(event) => update('agentId', event.target.value)} style={inputStyle} /></label>}{selected.credentials.includes('WEBHOOK_SECRET') && <label style={labelStyle}>Webhook Secret<input value={form.webhookSecret} onChange={(event) => update('webhookSecret', event.target.value)} style={inputStyle} /></label>}</div><AdminNotice>กรอกแล้ว {filledCredentials.length}/{selected.credentials.length} · ยังขาด {missingCredentials.map(credentialLabel).join(', ') || '-'}</AdminNotice></AdminCard><AdminCard title="URL API ที่จะสร้าง" description="เลือกเฉพาะที่ค่ายให้มา"><AdminStack>{selected.endpoints.map((endpoint) => <AdminRow key={endpoint}><label style={checkStyle}><input type="checkbox" checked={form.enabledEndpoints.includes(endpoint)} onChange={() => toggleEndpoint(endpoint)} /> {endpointLabel(endpoint)}</label><span style={monoStyle}>{`${form.baseUrl.replace(/\/+$/, '')}/${endpoint.toLowerCase().replaceAll('_', '-')}`}</span></AdminRow>)}</AdminStack></AdminCard><AdminCard title="ค่าเริ่มต้นที่ปลอดภัย" description="สร้างแบบยังไม่เปิดเงินจริง"><div style={tagRowStyle}>{selected.gates.map((item) => <AdminBadge key={item} tone="success">{gateLabel(item)}</AdminBadge>)}<AdminBadge tone="danger">เงินจริงปิด</AdminBadge><AdminBadge tone="warning">ค่ายปิดอยู่</AdminBadge></div></AdminCard></AdminGrid>
    <AdminCard title="สร้างค่าย" description="ตรวจแล้วค่อยกด ระบบจะเขียนค่าย/URL/API Key ลงฐานข้อมูล"><AdminRow><div><strong>{form.name}</strong><p style={mutedStyle}>{form.code} · URL {endpointPreview.length} รายการ · API Key/Secret {filledCredentials.length}/{selected.credentials.length}</p></div><AdminButton onClick={applyPreset} disabled={working}>{working ? 'กำลังสร้าง...' : 'สร้างค่าย'}</AdminButton></AdminRow></AdminCard>
  </AdminPage>;
}
function credentialValue(credential: string, form: { apiKey: string; secretKey: string; merchantId: string; agentId: string; webhookSecret: string }) { if (credential === 'API_KEY') return form.apiKey; if (credential === 'SECRET_KEY') return form.secretKey; if (credential === 'MERCHANT_ID') return form.merchantId; if (credential === 'AGENT_ID') return form.agentId; if (credential === 'WEBHOOK_SECRET') return form.webhookSecret; return ''; }
function riskTone(risk: string) { if (risk === 'Safe') return 'success'; if (risk === 'Market' || risk === 'Advanced') return 'warning'; return 'danger'; }
function riskLabel(risk: string) { if (risk === 'Safe') return 'ปลอดภัย'; if (risk === 'Market') return 'ใช้งานทั่วไป'; if (risk === 'Advanced') return 'ขั้นสูง'; return 'เสี่ยงสูง'; }
function presetDescription(code: string) { const map: Record<string, string> = { 'demo-provider': 'ไว้ลองระบบแบบไม่ต่อค่ายจริง', 'simulator-provider': 'ไว้ทดสอบโยกเงินและ error จำลอง', 'generic-transfer': 'เหมาะกับค่ายที่มี API โยกเงินเข้า/ออก', 'generic-seamless': 'ใช้เมื่อค่ายเป็น seamless wallet', 'real-provider': 'สำหรับค่ายจริงที่ต้องปรับเอง' }; return map[code] ?? code; }
function endpointLabel(value: string) { const map: Record<string, string> = { LAUNCH: 'เปิดเกม', BALANCE: 'เช็กยอด', TRANSFER_IN: 'โยกเข้าเกม', TRANSFER_OUT: 'โยกกลับวอเลต', GAME_LIST: 'ดึงเกม', BET_HISTORY: 'ประวัติเกม', WEBHOOK: 'Webhook', HEALTH_CHECK: 'ทดสอบค่าย' }; return map[value] ?? value; }
function credentialLabel(value: string) { const map: Record<string, string> = { API_KEY: 'API Key', SECRET_KEY: 'Secret Key', MERCHANT_ID: 'Merchant ID', AGENT_ID: 'Agent ID', WEBHOOK_SECRET: 'Webhook Secret' }; return map[value] ?? value; }
function gateLabel(value: string) { const map: Record<string, string> = { launchEnabled: 'เปิดเกมได้', transferEnabled: 'โยกเงินได้', walletSyncEnabled: 'เชื่อมวอเลต', webhookSettlementEnabled: 'Webhook มีผลกับเงิน' }; return map[value] ?? value; }
const sectionTitleStyle = { margin: '24px 0 12px', fontSize: 'clamp(24px, 7vw, 34px)', lineHeight: 1 } as const;
const blockStyle = { display: 'grid', gap: 8 } as const;
const tagRowStyle = { display: 'flex', gap: 8, flexWrap: 'wrap' as const };
const formStyle = { display: 'grid', gap: 12 } as const;
const labelStyle = { display: 'grid', gap: 6, color: '#94a3b8', fontSize: 12, fontWeight: 900 } as const;
const checkStyle = { display: 'flex', gap: 8, alignItems: 'center', color: '#cbd5e1', fontWeight: 900 } as const;
const inputStyle = { width: '100%', minHeight: 44, borderRadius: 12, border: '1px solid rgba(148,163,184,.22)', background: '#0b1220', color: '#f8fafc', padding: '0 12px', boxSizing: 'border-box' as const, fontSize: 15 };
const monoStyle = { fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace', overflowWrap: 'anywhere' as const, color: '#cbd5e1', fontSize: 12 } as const;
const mutedStyle = { margin: 0, color: '#94a3b8', lineHeight: 1.55 } as const;
