ALTER TABLE "admin_users"
  ADD COLUMN IF NOT EXISTS "display_name" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "first_name" VARCHAR(80),
  ADD COLUMN IF NOT EXISTS "last_name" VARCHAR(80),
  ADD COLUMN IF NOT EXISTS "position" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "department" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "avatar_url" TEXT;
