export const ADMIN_ROLE_TEMPLATE_CODES = [
  'finance',
  'deposit_withdrawal',
  'marketing',
  'manager',
  'system_admin',
] as const;

export type AdminRoleTemplateCode = (typeof ADMIN_ROLE_TEMPLATE_CODES)[number];

export type AdminRoleTemplate = {
  code: AdminRoleTemplateCode;
  name: string;
  description: string;
  level: number;
  positionLabel: string;
  permissionCodes: readonly string[];
};

export const ADMIN_ROLE_TEMPLATES: readonly AdminRoleTemplate[] = [
  {
    code: 'finance',
    name: 'Finance',
    description: 'ดูภาพรวมการเงิน กระเป๋า รายงาน และความเสี่ยง โดยไม่มีสิทธิ์อนุมัติฝากถอนขั้นสุดท้าย',
    level: 40,
    positionLabel: 'การเงิน',
    permissionCodes: [
      'wallet.view',
      'topups.view',
      'deposit.view',
      'withdraw.view',
      'bank_accounts.view',
      'risk.view',
      'reports.view',
      'reports.export',
    ],
  },
  {
    code: 'deposit_withdrawal',
    name: 'Deposit & Withdrawal',
    description: 'ปฏิบัติงานฝาก ถอน บัญชีธนาคาร และคิวตรวจสอบความเสี่ยงตามลำดับงาน',
    level: 35,
    positionLabel: 'ฝากถอน',
    permissionCodes: [
      'wallet.view',
      'topups.view',
      'topups.review',
      'topups.approve',
      'topups.reject',
      'deposit.view',
      'deposit.claim',
      'deposit.approve',
      'deposit.reject',
      'withdraw.view',
      'withdraw.claim',
      'withdraw.success',
      'withdraw.reject',
      'bank_accounts.view',
      'bank_accounts.review',
      'risk.view',
      'risk.assign',
      'risk.note',
    ],
  },
  {
    code: 'marketing',
    name: 'Marketing',
    description: 'จัดการโปรโมชัน แคมเปญ ฟีเจอร์การตลาด และรายงานที่เกี่ยวข้อง',
    level: 50,
    positionLabel: 'การตลาด',
    permissionCodes: [
      'users.view',
      'promotion.view',
      'promotion.create',
      'promotions.claims.view',
      'promotions.claims.review',
      'bonus.ledger.view',
      'bonus.turnover.update',
      'bonus.lifecycle.update',
      'affiliate.view',
      'affiliate.review',
      'commission.view',
      'commission.create',
      'commission.review',
      'settings.features.view',
      'settings.features.update',
      'reports.view',
      'reports.export',
    ],
  },
  {
    code: 'manager',
    name: 'Manager',
    description: 'บริหารทีม สร้างผู้ใต้บังคับบัญชา จัดบทบาท และดูภาพรวมงานโดยแจกสิทธิ์ได้ไม่เกินสิทธิ์ตนเอง',
    level: 20,
    positionLabel: 'หัวหน้า',
    permissionCodes: [
      'users.view',
      'users.update',
      'users.suspend',
      'admin.view',
      'admin.create',
      'admin.access.view',
      'admin.access.manage',
      'admin.teams.view',
      'admin.teams.manage',
      'admin.subordinates.create',
      'admin.subordinates.manage',
      'admin.permissions.override',
      'roles.update',
      'reports.view',
      'reports.export',
    ],
  },
  {
    code: 'system_admin',
    name: 'System Administrator',
    description: 'ดูแลระบบ ผู้ให้บริการ เกม การตั้งค่า ความปลอดภัย และโครงสร้างสิทธิ์โดยไม่ถือสิทธิ์การเงินขั้นสุดท้าย',
    level: 15,
    positionLabel: 'คนดูแลระบบ',
    permissionCodes: [
      'admin.view',
      'admin.create',
      'admin.access.view',
      'admin.access.manage',
      'admin.access.delegate',
      'admin.teams.view',
      'admin.teams.manage',
      'admin.subordinates.create',
      'admin.subordinates.manage',
      'admin.permissions.override',
      'roles.update',
      'provider.view',
      'provider.update',
      'game.providers.view',
      'game.providers.manage',
      'seo.view',
      'seo.update',
      'settings.update',
      'settings.website.view',
      'settings.website.update',
      'settings.branding.view',
      'settings.branding.update',
      'settings.branding.publish',
      'settings.theme.view',
      'settings.theme.update',
      'settings.seo.view',
      'settings.seo.update',
      'settings.contact.view',
      'settings.contact.update',
      'settings.maintenance.view',
      'settings.maintenance.update',
      'settings.scripts.view',
      'settings.scripts.update',
      'settings.features.view',
      'settings.features.update',
      'settings.legal.view',
      'settings.legal.update',
      'security.anti_bot.view',
      'security.anti_bot.update',
      'security.anti_bot.test',
      'security.anti_bot.override',
      'reports.view',
      'reports.export',
    ],
  },
] as const;

export const ADMIN_ROLE_TEMPLATE_CODE_SET = new Set<string>(ADMIN_ROLE_TEMPLATE_CODES);

export function getAdminRoleTemplate(code: string) {
  return ADMIN_ROLE_TEMPLATES.find((template) => template.code === code) ?? null;
}
