import type { AdminActor } from '../../common/actors';
import { buildAdminAuditData } from '../../common/audit/admin-audit.builder';
import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createDecipheriv, createHmac, createHash } from 'crypto';
import { PrismaService } from '../../database/prisma.service';
import { GameProviderEndpointType, GameProviderWalletMode } from './game-platform.types';
import { ProviderAdapterContext } from './provider-adapter.interface';
import { ProviderAdapterRegistry } from './adapters/provider-adapter.registry';

type TestMethod = 'healthCheck' | 'launchGame' | 'getBalance' | 'transferIn' | 'transferOut' | 'syncGames' | 'getBetHistory' | 'validateWebhook' | 'parseWebhook';
type TestMode = 'SAFE' | 'PRODUCTION';
type RequestMeta = { ipAddress?: string; userAgent?: string };
type ProviderForAdapter = { code: string; walletMode: GameProviderWalletMode; currency: string; metadata?: unknown; endpoints: Array<{ type: GameProviderEndpointType; url: string; timeoutMs: number }>; credentials: Array<{ type: string; maskedValue: string; encryptedValue?: string }> };

@Injectable()
export class AdapterTestService {
  constructor(private readonly prisma: PrismaService, private readonly registry: ProviderAdapterRegistry, private readonly configService: ConfigService) {}
  async listMethods(providerId: string) { const provider = await this.provider(providerId); return { provider: { code: provider.code, adapterRegistered: this.registry.hasAdapter(provider.code) }, methods: ['healthCheck', 'launchGame', 'getBalance', 'transferIn', 'transferOut', 'syncGames', 'getBetHistory', 'validateWebhook', 'parseWebhook'] satisfies TestMethod[] }; }
  async history(providerId: string) { await this.provider(providerId); const rows = await this.prisma.adminAuditLog.findMany({ where: { module: 'game-platform', action: 'game_provider.adapter_test', targetId: providerId }, orderBy: { createdAt: 'desc' }, take: 20, include: { adminUser: { select: { id: true, username: true } } } }); return { items: rows.map((row) => { const data = this.record(row.newData); return { id: row.id, method: typeof data.method === 'string' ? data.method : '-', testMode: data.testMode === 'PRODUCTION' ? 'PRODUCTION' : 'SAFE', environment: typeof data.environment === 'string' ? data.environment : '-', ok: data.ok !== false, latencyMs: Number.isFinite(Number(data.latencyMs)) ? Number(data.latencyMs) : null, createdAt: row.createdAt, adminUser: row.adminUser }; }) }; }
  async run(providerId: string, method: TestMethod, payload: Record<string, unknown> = {}, actor: AdminActor, meta: RequestMeta) {
    const provider = await this.provider(providerId); const testMode: TestMode = payload.testMode === 'PRODUCTION' ? 'PRODUCTION' : 'SAFE'; const input = { ...payload }; delete input.testMode; const environment = this.environment(provider); const started = Date.now();
    try {
      this.assertTestMode(provider, method, testMode);
      const adapter = this.registry.getAdapter(provider.code); const context = this.context(provider); const idempotencyKey = String(input.idempotencyKey ?? `adapter_test_${Date.now()}`); let result: unknown;
      if (method === 'healthCheck') result = await adapter.healthCheck(context);
      else if (method === 'launchGame') result = await adapter.launchGame(context, { userId: String(input.userId ?? 'adapter-test-user'), gameCode: String(input.gameCode ?? 'demo-slot-001'), sessionId: String(input.sessionId ?? `adapter-test-session-${Date.now()}`), ipAddress: String(input.ipAddress ?? '127.0.0.1'), userAgent: String(input.userAgent ?? 'adapter-test-harness'), returnUrl: typeof input.returnUrl === 'string' ? input.returnUrl : undefined });
      else if (method === 'getBalance') result = await adapter.getBalance(context, { userId: String(input.userId ?? 'adapter-test-user'), providerUserId: typeof input.providerUserId === 'string' ? input.providerUserId : undefined });
      else if (method === 'transferIn') result = await adapter.transferIn(context, { userId: String(input.userId ?? 'adapter-test-user'), providerUserId: typeof input.providerUserId === 'string' ? input.providerUserId : undefined, amount: String(input.amount ?? '1.00'), currency: String(input.currency ?? provider.currency), idempotencyKey, sessionId: typeof input.sessionId === 'string' ? input.sessionId : undefined });
      else if (method === 'transferOut') result = await adapter.transferOut(context, { userId: String(input.userId ?? 'adapter-test-user'), providerUserId: typeof input.providerUserId === 'string' ? input.providerUserId : undefined, amount: String(input.amount ?? '1.00'), currency: String(input.currency ?? provider.currency), idempotencyKey, sessionId: typeof input.sessionId === 'string' ? input.sessionId : undefined });
      else if (method === 'syncGames') result = await adapter.syncGames(context);
      else if (method === 'getBetHistory') result = await adapter.getBetHistory(context, { from: String(input.from ?? new Date(Date.now() - 86400000).toISOString()), to: String(input.to ?? new Date().toISOString()), cursor: typeof input.cursor === 'string' ? input.cursor : undefined });
      else if (method === 'validateWebhook') { const body = input.body ?? { eventType: 'adapter.test', idempotencyKey }; const timestamp = String(input.timestamp ?? new Date().toISOString()); const signature = typeof input.signature === 'string' ? input.signature : this.sign(context, body, timestamp); result = await adapter.validateWebhook(context, { 'x-timestamp': timestamp, 'x-signature': signature, 'x-provider-timestamp': timestamp, 'x-provider-signature': signature }, body); }
      else if (method === 'parseWebhook') result = await adapter.parseWebhook(context, input.body ?? { eventType: 'adapter.test', idempotencyKey, providerTransactionId: `tx_${idempotencyKey}` });
      else throw new BadRequestException('Unsupported adapter test method');
      const response = { ok: true, provider: { id: providerId, code: provider.code }, method, testMode, environment, latencyMs: Date.now() - started, result: this.sanitize(result), input: this.sanitize(input), checkedAt: new Date().toISOString() };
      await this.audit(actor, providerId, { method, testMode, environment, ok: this.record(result).ok !== false, latencyMs: response.latencyMs, checkedAt: response.checkedAt }, meta);
      return response;
    } catch (error) {
      await this.audit(actor, providerId, { method, testMode, environment, ok: false, errorCode: error instanceof BadRequestException ? 'REQUEST_REJECTED' : 'ADAPTER_TEST_FAILED', latencyMs: Date.now() - started, checkedAt: new Date().toISOString() }, meta);
      if (error instanceof BadRequestException || error instanceof NotFoundException) throw error;
      throw new BadRequestException('Adapter test failed');
    }
  }
  private isSafeTransferTestProvider(providerCode: string) { return new Set(['demo-provider', 'demo-provider-uat', 'simulator-provider']).has(providerCode.trim().toLowerCase()); }
  private assertTestMode(provider: ProviderForAdapter, method: TestMethod, testMode: TestMode) { const environment = this.environment(provider); const isTransfer = method === 'transferIn' || method === 'transferOut'; if (isTransfer && !this.isSafeTransferTestProvider(provider.code)) throw new BadRequestException('Transfer adapter tests are restricted to demo/simulator providers'); if (testMode === 'PRODUCTION') { if (environment !== 'PRODUCTION') throw new BadRequestException('Production tests require a production provider'); if (isTransfer) throw new BadRequestException('Production tests cannot transfer money'); return; } if (environment === 'PRODUCTION' && !new Set<TestMethod>(['healthCheck', 'validateWebhook', 'parseWebhook']).has(method)) throw new BadRequestException('Safe tests on production are limited to health and webhook checks'); }
  private environment(provider: ProviderForAdapter) { const metadata = this.record(provider.metadata); const declared = typeof metadata.environment === 'string' ? metadata.environment.toUpperCase() : ''; if (declared === 'PRODUCTION' || declared === 'UAT' || declared === 'DEMO') return declared; const code = provider.code.trim().toLowerCase(); if (code.endsWith('-uat')) return 'UAT'; if (code.startsWith('demo-') || code.startsWith('simulator-')) return 'DEMO'; return 'PRODUCTION'; }
  private async provider(providerId: string) { const item = await this.prisma.gameProvider.findUnique({ where: { id: providerId }, include: { endpoints: { where: { isEnabled: true }, orderBy: { type: 'asc' } }, credentials: { where: { isEnabled: true }, orderBy: { type: 'asc' }, select: { id: true, type: true, maskedValue: true, encryptedValue: true, isEnabled: true } } } }); if (!item) throw new NotFoundException('Game provider not found'); return item; }
  private context(provider: ProviderForAdapter): ProviderAdapterContext { const endpointMap = provider.endpoints.reduce<Partial<Record<GameProviderEndpointType, string>>>((map, endpoint) => { map[endpoint.type] = endpoint.url; return map; }, {}); const credentialMap = provider.credentials.reduce<Record<string, string>>((map, credential) => { map[credential.type] = credential.encryptedValue ? this.decrypt(credential.encryptedValue) : credential.maskedValue; return map; }, {}); return { providerCode: provider.code, baseUrl: endpointMap.HEALTH_CHECK ?? endpointMap.LAUNCH ?? '', walletMode: provider.walletMode, currency: provider.currency, timeoutMs: Math.max(...provider.endpoints.map((endpoint) => endpoint.timeoutMs), 10000), endpointMap, credentialMap }; }
  private decrypt(value: string) { const [, ivRaw, tagRaw, encryptedRaw] = value.split(':'); if (!ivRaw || !tagRaw || !encryptedRaw) return value; const decipher = createDecipheriv('aes-256-gcm', this.credentialKey(), Buffer.from(ivRaw, 'base64')); decipher.setAuthTag(Buffer.from(tagRaw, 'base64')); return Buffer.concat([decipher.update(Buffer.from(encryptedRaw, 'base64')), decipher.final()]).toString('utf8'); }
  private credentialKey() { const keySource = this.configService.get<string>('GAME_CREDENTIAL_SECRET') ?? this.configService.get<string>('JWT_ACCESS_KEY') ?? 'local_game_credential_key'; return createHash('sha256').update(keySource).digest(); }
  private sign(context: ProviderAdapterContext, body: unknown, timestamp: string) { const secret = context.credentialMap.SECRET_KEY || context.credentialMap.WEBHOOK_SECRET || context.credentialMap.API_KEY || 'adapter-test-secret'; return createHmac('sha256', secret).update(`${timestamp}.${JSON.stringify(body)}`).digest('hex'); }
  private record(value: unknown) { return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
  private async audit(actor: AdminActor, providerId: string, data: Record<string, unknown>, meta: RequestMeta) { await this.prisma.adminAuditLog.create({ data: buildAdminAuditData({ adminUserId: actor.id, module: 'game-platform', action: 'game_provider.adapter_test', targetId: providerId, newData: data, ipAddress: meta.ipAddress, userAgent: meta.userAgent }) }); }
  private sanitize(value: unknown) { return JSON.parse(JSON.stringify(value, (key, item) => /api.?key|secret|signature|encryptedvalue|credentialmap/i.test(key) ? '[REDACTED]' : item)); }
}
