import type { AdminActor, MemberActor } from '../../common/actors';
import { buildAdminAuditData } from '../../common/audit/admin-audit.builder';
import { Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../database/prisma.service';
import { ProviderAdapterRegistry } from './adapters/provider-adapter.registry';

type ProviderGates = Partial<Record<'launchEnabled' | 'transferEnabled' | 'realMoneyEnabled' | 'webhookSettlementEnabled' | 'walletSyncEnabled', boolean>>;

@Injectable()
export class GamePlatformMoneyService {
  constructor(private readonly prisma: PrismaService, private readonly adapterRegistry: ProviderAdapterRegistry) {}

  async updateProviderGates(providerId: string, actor: AdminActor, gates: ProviderGates) { const provider = await this.prisma.gameProvider.findUnique({ where: { id: providerId } }); if (!provider) throw new NotFoundException('Game provider not found'); const current = this.objectJson(provider.metadata); const next = { ...current, ...gates, gateUpdatedBy: actor.id, gateUpdatedAt: new Date().toISOString() }; const item = await this.prisma.gameProvider.update({ where: { id: providerId }, data: { metadata: this.safeJson(next) }, select: { id: true, name: true, code: true, metadata: true } }); await this.audit(actor, 'game.provider.gates.update', 'game_platform', providerId, { before: current, after: item.metadata }); return { ok: true, item, gates: this.extractGates(item.metadata) }; }
  async realMoneyPreflight(providerId: string) { const panel = await this.providerRiskPanel(providerId); const unresolvedMismatchCount = await this.prisma.providerWalletSnapshot.count({ where: { providerId, status: { in: ['MISMATCH', 'UNKNOWN'] } } }); const blockers = [...panel.checks.filter((item) => !item.ok).map((item) => item.key)]; if (!panel.flags.transferEnabled) blockers.push('transferEnabled_false'); if (!panel.flags.walletSyncEnabled) blockers.push('walletSyncEnabled_false'); if (!panel.flags.realMoneyEnabled) blockers.push('realMoneyEnabled_false'); if (!panel.flags.webhookSettlementEnabled) blockers.push('webhookSettlementEnabled_false'); if (unresolvedMismatchCount > 0) blockers.push('unresolved_mismatch'); return { ok: blockers.length === 0, provider: panel.provider, flags: panel.flags, blockers, unresolvedMismatchCount, riskStatus: panel.status, checks: panel.checks }; }
  async reviewTransfer(id: string, actor: AdminActor, note: string) { const current = await this.prisma.gameTransfer.findUnique({ where: { id } }); if (!current) throw new NotFoundException('Game transfer not found'); const payload = this.mergeJson(current.responsePayload, { manualReview: { note, reviewedBy: actor.id, reviewedAt: new Date().toISOString() } }); const item = await this.prisma.gameTransfer.update({ where: { id }, data: { responsePayload: payload }, include: { user: { select: { id: true, username: true, phone: true } }, provider: { select: { id: true, name: true, code: true } } } }); await this.audit(actor, 'game.transfer.review', 'game_platform', id, { note }); return { ok: true, item }; }
  async providerRiskPanel(providerId: string) { const provider = await this.prisma.gameProvider.findUnique({ where: { id: providerId }, include: { endpoints: { orderBy: { type: 'asc' } }, credentials: { orderBy: { type: 'asc' }, select: this.credentialSelect() } } }); if (!provider) throw new NotFoundException('Game provider not found'); const [failedTransferCount, duplicateWebhookCount, latestSnapshot, unresolvedMismatchCount] = await Promise.all([this.prisma.gameTransfer.count({ where: { providerId, status: 'FAILED' } }), this.prisma.webhookLog.count({ where: { providerId, status: 'DUPLICATE' } }), this.prisma.providerWalletSnapshot.findFirst({ where: { providerId }, orderBy: { checkedAt: 'desc' } }), this.prisma.providerWalletSnapshot.count({ where: { providerId, status: { in: ['MISMATCH', 'UNKNOWN'] } } })]); const endpointSet = new Set(provider.endpoints.filter((item) => item.isEnabled).map((item) => item.type)); const credentialSet = new Set(provider.credentials.filter((item) => item.isEnabled).map((item) => item.type)); const flags = this.extractGates(provider.metadata); const checks = [{ key: 'adapter_registered', ok: this.adapterRegistry.hasAdapter(provider.code) }, { key: 'provider_active', ok: provider.status === 'ACTIVE' }, { key: 'transfer_wallet_mode', ok: provider.walletMode === 'TRANSFER' || provider.walletMode === 'HYBRID' }, { key: 'wallet_sync_enabled', ok: flags.walletSyncEnabled }, { key: 'launch_endpoint', ok: endpointSet.has('LAUNCH') }, { key: 'balance_endpoint', ok: endpointSet.has('BALANCE') }, { key: 'transfer_in_endpoint', ok: endpointSet.has('TRANSFER_IN') }, { key: 'transfer_out_endpoint', ok: endpointSet.has('TRANSFER_OUT') }, { key: 'webhook_endpoint', ok: endpointSet.has('WEBHOOK') }, { key: 'api_key', ok: credentialSet.has('API_KEY') }, { key: 'webhook_secret', ok: credentialSet.has('WEBHOOK_SECRET') }, { key: 'latest_reconciliation_safe', ok: !latestSnapshot || latestSnapshot.status === 'MATCHED' }, { key: 'no_unresolved_mismatch', ok: unresolvedMismatchCount === 0 }, { key: 'real_money_disabled_by_default', ok: !flags.realMoneyEnabled }]; const status = flags.realMoneyEnabled ? 'NEEDS_REVIEW' : checks.every((item) => item.ok) ? 'WALLET_SYNC_READY' : 'BLOCKED'; return { provider: { id: provider.id, name: provider.name, code: provider.code, status: provider.status }, flags, checks, status, failedTransferCount, duplicateWebhookCount, latestSnapshot, unresolvedMismatchCount }; }
  async listMemberSessionTransfers(sessionId: string, actor: MemberActor) { const session = await this.prisma.gameSession.findFirst({ where: { id: sessionId, userId: actor.id }, select: { id: true } }); if (!session) throw new NotFoundException('Game session not found'); const items = await this.prisma.gameTransfer.findMany({ where: { sessionId, userId: actor.id }, orderBy: { createdAt: 'desc' }, take: 30, select: { id: true, type: true, status: true, amount: true, currency: true, idempotencyKey: true, providerTransactionId: true, errorCode: true, errorMessage: true, createdAt: true, resolvedAt: true, responsePayload: true } }); return { items }; }
  async listTransfers() { const items = await this.prisma.gameTransfer.findMany({ orderBy: { createdAt: 'desc' }, take: 100, include: this.transferInclude() }); return { items, summary: { total: items.length, success: items.filter((item) => item.status === 'SUCCESS').length, failed: items.filter((item) => item.status === 'FAILED').length, pending: items.filter((item) => item.status === 'PENDING').length } }; }
  async getTransfer(id: string) { const item = await this.prisma.gameTransfer.findUnique({ where: { id }, include: this.transferInclude() }); if (!item) throw new NotFoundException('Game transfer not found'); return item; }
  private credentialSelect() { return { id: true, providerId: true, type: true, maskedValue: true, encryptedValue: true, isEnabled: true, rotatedAt: true, createdAt: true, updatedAt: true } as const; }
  private extractGates(metadata: unknown) { const value = this.objectJson(metadata); return { launchEnabled: value.launchEnabled !== false, transferEnabled: value.transferEnabled === true, realMoneyEnabled: value.realMoneyEnabled === true, webhookSettlementEnabled: value.webhookSettlementEnabled === true, walletSyncEnabled: value.walletSyncEnabled !== false }; }
  private transferInclude() { return { user: { select: { id: true, username: true, phone: true } }, provider: { select: { id: true, name: true, code: true } }, session: { select: { id: true, providerSessionId: true, game: { select: { id: true, name: true, providerGameCode: true } } } } } as const; }
  private async audit(actor: AdminActor, action: string, module: string, targetId: string | undefined, newData: unknown) { await this.prisma.adminAuditLog.create({ data: buildAdminAuditData({ adminUserId: actor.id, action, module, targetId, newData }) }); }
  private safeJson(value: unknown) { return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue; }
  private objectJson(value: unknown) { return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
  private mergeJson(current: unknown, patch: Record<string, unknown>) { return this.safeJson({ ...this.objectJson(current), ...patch }); }
}
