import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Prisma } from '@prisma/client';
import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'crypto';
import { PrismaService } from '../../database/prisma.service';
import { GameProviderEndpointType, GameProviderWalletMode } from './game-platform.types';
import { NormalizedGameProviderInput } from './dto/game-provider.dto';
import { NormalizedGameProviderEndpointInput } from './dto/game-provider-endpoint.dto';
import { NormalizedGameProviderCredentialInput, NormalizedGameProviderCredentialUpdate } from './dto/game-provider-credential.dto';
import { NormalizedGameInput } from './dto/game-catalog.dto';
import { NormalizedGameMediaInput } from './dto/game-media.dto';
import { ProviderAdapterContext, ProviderGamePayload } from './provider-adapter.interface';
import { ProviderAdapterRegistry } from './adapters/provider-adapter.registry';

const DATA_MODELS = ['GameProvider', 'GameProviderEndpoint', 'GameProviderCredential', 'Game', 'GameMedia', 'GameSession', 'GameTransfer', 'ProviderWalletSnapshot', 'WebhookLog'] as const;
const ADAPTER_METHODS = ['healthCheck', 'launchGame', 'getBalance', 'transferIn', 'transferOut', 'syncGames', 'getBetHistory', 'validateWebhook', 'parseWebhook'] as const;
type AdminActor = { id: string };
type MemberActor = { id: string };
type RequestMeta = { ipAddress?: string; userAgent?: string };

@Injectable()
export class GamePlatformService {
  constructor(private readonly prisma: PrismaService, private readonly configService: ConfigService, private readonly adapterRegistry: ProviderAdapterRegistry) {}
  overview() { return { status: 'scaffold', models: DATA_MODELS, adapterMethods: ADAPTER_METHODS, registeredAdapters: this.adapterRegistry.listAdapterCodes(), walletModes: ['SEAMLESS', 'TRANSFER', 'HYBRID'] satisfies GameProviderWalletMode[], endpointTypes: ['LAUNCH', 'BALANCE', 'TRANSFER_IN', 'TRANSFER_OUT', 'GAME_LIST', 'BET_HISTORY', 'WEBHOOK', 'HEALTH_CHECK'] satisfies GameProviderEndpointType[], note: 'Launch/session and wallet transfer scaffolds are enabled for registered adapters. Use provider presets and preflight before real money.' }; }
  dataModelPlan() { return { provider: ['profile', 'status', 'walletMode', 'currency', 'timezone', 'sortOrder', 'metadata'], endpoint: ['providerId', 'type', 'url', 'method', 'timeoutMs', 'retryCount', 'isEnabled'], credential: ['providerId', 'type', 'encryptedValue', 'maskedValue', 'rotatedAt', 'isEnabled'], game: ['providerId', 'providerGameCode', 'name', 'category', 'status', 'flags', 'sortOrder', 'metadata'], media: ['gameId', 'providerId', 'type', 'sourceUrl', 'cachedUrl', 'status', 'isOverride'], session: ['userId', 'providerId', 'gameId', 'status', 'launchUrl', 'providerSessionId', 'ipAddress', 'userAgent'], transfer: ['userId', 'providerId', 'sessionId', 'type', 'status', 'amount', 'idempotencyKey', 'providerTransactionId'], walletSnapshot: ['userId', 'providerId', 'systemBalance', 'providerBalance', 'difference', 'status', 'checkedAt'], webhook: ['providerId', 'eventType', 'status', 'signatureValid', 'idempotencyKey', 'providerTransactionId', 'error'] }; }
  async listProviders() { const items = await this.prisma.gameProvider.findMany({ orderBy: [{ sortOrder: 'asc' }, { name: 'asc' }], include: { _count: { select: { endpoints: true, credentials: true, games: true, sessions: true, transfers: true, webhookLogs: true } } } }); return { items }; }
  async getProvider(id: string) { const item = await this.prisma.gameProvider.findUnique({ where: { id }, include: { endpoints: { orderBy: { type: 'asc' } }, credentials: { orderBy: { type: 'asc' }, select: this.credentialSelect() }, media: { orderBy: { createdAt: 'desc' }, take: 20 }, _count: { select: { games: true, sessions: true, transfers: true, walletSnapshots: true, webhookLogs: true } } } }); if (!item) throw new NotFoundException('Game provider not found'); return { ...item, readiness: this.providerReadiness(item), adapterRegistered: this.adapterRegistry.hasAdapter(item.code) }; }
  async createProvider(input: NormalizedGameProviderInput, actor: AdminActor, meta: RequestMeta) { try { const item = await this.prisma.gameProvider.create({ data: input as Prisma.GameProviderCreateInput }); await this.audit(actor, 'game_provider.create', item.id, null, this.safeJson(item), meta); return item; } catch (error) { this.handleProviderWriteError(error, 'Game provider code already exists'); } }
  async updateProvider(id: string, input: Partial<NormalizedGameProviderInput>, actor: AdminActor, meta: RequestMeta) { const current = await this.prisma.gameProvider.findUnique({ where: { id } }); if (!current) throw new NotFoundException('Game provider not found'); try { const item = await this.prisma.gameProvider.update({ where: { id }, data: input as Prisma.GameProviderUpdateInput }); await this.audit(actor, 'game_provider.update', item.id, this.safeJson(current), this.safeJson(item), meta); return item; } catch (error) { this.handleProviderWriteError(error, 'Game provider code already exists'); } }
  async listGames() { const items = await this.prisma.game.findMany({ orderBy: [{ sortOrder: 'asc' }, { name: 'asc' }], include: { provider: { select: { id: true, name: true, code: true, status: true } }, media: { orderBy: [{ isOverride: 'desc' }, { createdAt: 'desc' }], take: 6 } } }); const summary = { total: items.length, active: items.filter((item) => item.status === 'ACTIVE').length, featured: items.filter((item) => item.isFeatured).length, popular: items.filter((item) => item.isPopular).length }; return { items, summary }; }
  async getGame(id: string) { const item = await this.prisma.game.findUnique({ where: { id }, include: { provider: { select: { id: true, name: true, code: true, status: true } }, media: { orderBy: [{ isOverride: 'desc' }, { createdAt: 'desc' }] } } }); if (!item) throw new NotFoundException('Game not found'); return item; }
  async createGame(input: NormalizedGameInput, actor: AdminActor, meta: RequestMeta) { await this.assertProvider(input.providerId); try { const item = await this.prisma.game.create({ data: this.gameData(input) as Prisma.GameUncheckedCreateInput, include: { provider: { select: { id: true, name: true, code: true, status: true } } } }); await this.audit(actor, 'game.create', item.id, null, this.safeJson(item), meta); return item; } catch (error) { this.handleProviderWriteError(error, 'Game code already exists for this provider'); } }
  async updateGame(id: string, input: Partial<NormalizedGameInput>, actor: AdminActor, meta: RequestMeta) { const current = await this.prisma.game.findUnique({ where: { id } }); if (!current) throw new NotFoundException('Game not found'); if (input.providerId) await this.assertProvider(input.providerId); try { const item = await this.prisma.game.update({ where: { id }, data: this.gameData(input) as Prisma.GameUpdateInput, include: { provider: { select: { id: true, name: true, code: true, status: true } } } }); await this.audit(actor, 'game.update', item.id, this.safeJson(current), this.safeJson(item), meta); return item; } catch (error) { this.handleProviderWriteError(error, 'Game code already exists for this provider'); } }
  async createGameMedia(gameId: string, input: NormalizedGameMediaInput, actor: AdminActor, meta: RequestMeta) { const game = await this.prisma.game.findUnique({ where: { id: gameId }, select: { id: true, providerId: true } }); if (!game) throw new NotFoundException('Game not found'); const item = await this.prisma.gameMedia.create({ data: { gameId, providerId: game.providerId, ...this.mediaData(input) } as Prisma.GameMediaUncheckedCreateInput }); await this.audit(actor, 'game_media.create', item.id, null, this.safeJson(item), meta); return item; }
  async updateGameMedia(gameId: string, mediaId: string, input: Partial<NormalizedGameMediaInput>, actor: AdminActor, meta: RequestMeta) { const current = await this.prisma.gameMedia.findFirst({ where: { id: mediaId, gameId } }); if (!current) throw new NotFoundException('Game media not found'); const item = await this.prisma.gameMedia.update({ where: { id: mediaId }, data: this.mediaData(input) as Prisma.GameMediaUpdateInput }); await this.audit(actor, 'game_media.update', item.id, this.safeJson(current), this.safeJson(item), meta); return item; }
  async syncGamesDryRun(providerId: string, actor: AdminActor, meta: RequestMeta) { const provider = await this.prisma.gameProvider.findUnique({ where: { id: providerId }, include: { endpoints: { where: { isEnabled: true }, orderBy: { type: 'asc' } }, credentials: { where: { isEnabled: true }, orderBy: { type: 'asc' }, select: this.credentialSecretSelect() } } }); if (!provider) throw new NotFoundException('Game provider not found'); const adapter = this.adapterRegistry.getAdapter(provider.code); const result = await adapter.syncGames(this.buildAdapterContext(provider)); if (!result.ok || !result.payload) { await this.audit(actor, 'game_provider.sync_games.failed', provider.id, null, this.safeJson({ ok: result.ok, errorCode: result.errorCode, errorMessage: result.errorMessage }), meta); return { ok: false, providerCode: provider.code, created: 0, updated: 0, skipped: 0, errorCode: result.errorCode, errorMessage: result.errorMessage }; } let created = 0; let updated = 0; let skipped = 0; for (const payload of result.payload) { const outcome = await this.upsertProviderGame(provider.id, payload); created += outcome === 'created' ? 1 : 0; updated += outcome === 'updated' ? 1 : 0; skipped += outcome === 'skipped' ? 1 : 0; } const response = { ok: true, providerCode: provider.code, requestId: result.requestId, created, updated, skipped, total: result.payload.length, checkedAt: new Date().toISOString() }; await this.audit(actor, 'game_provider.sync_games.dry_run', provider.id, null, this.safeJson(response), meta); return response; }
  async listMemberGames() { const items = await this.prisma.game.findMany({ where: { status: 'ACTIVE', provider: { status: 'ACTIVE' } }, orderBy: [{ isFeatured: 'desc' }, { isPopular: 'desc' }, { sortOrder: 'asc' }, { name: 'asc' }], include: { provider: { select: { id: true, name: true, code: true } }, media: { where: { status: { in: ['READY', 'FALLBACK'] } }, orderBy: [{ isOverride: 'desc' }, { createdAt: 'desc' }], take: 6 } } }); const categories = Array.from(new Set(items.map((item) => item.category))).sort(); return { items, categories, featured: items.filter((item) => item.isFeatured), newest: items.filter((item) => item.isNew), popular: items.filter((item) => item.isPopular) }; }
  async launchMemberGame(gameId: string, actor: MemberActor, meta: RequestMeta) { const game = await this.prisma.game.findFirst({ where: { id: gameId, status: 'ACTIVE', provider: { status: 'ACTIVE' } }, include: { provider: { include: { endpoints: { where: { isEnabled: true }, orderBy: { type: 'asc' } }, credentials: { where: { isEnabled: true }, orderBy: { type: 'asc' }, select: this.credentialSecretSelect() } } } } }); if (!game) throw new NotFoundException('Game is not available'); const session = await this.prisma.gameSession.create({ data: { userId: actor.id, providerId: game.providerId, gameId: game.id, status: 'CREATED', ipAddress: meta.ipAddress, userAgent: meta.userAgent } }); const adapter = this.adapterRegistry.getAdapter(game.provider.code); const result = await adapter.launchGame(this.buildAdapterContext(game.provider), { userId: actor.id, gameCode: game.providerGameCode, sessionId: session.id, ipAddress: meta.ipAddress, userAgent: meta.userAgent }); if (!result.ok || !result.payload?.launchUrl) { const failed = await this.prisma.gameSession.update({ where: { id: session.id }, data: { status: 'FAILED', errorCode: result.errorCode ?? 'LAUNCH_FAILED', errorMessage: result.errorMessage ?? 'Provider launch failed' } }); return { ok: false, session: failed, errorCode: failed.errorCode, errorMessage: failed.errorMessage }; } const launched = await this.prisma.gameSession.update({ where: { id: session.id }, data: { status: 'LAUNCHED', launchUrl: result.payload.launchUrl, providerSessionId: result.payload.providerSessionId, startedAt: new Date() }, include: { game: { select: { id: true, name: true, providerGameCode: true } }, provider: { select: { id: true, name: true, code: true } } } }); return { ok: true, session: launched, launchUrl: result.payload.launchUrl, providerSessionId: result.payload.providerSessionId, expiresAt: result.payload.expiresAt }; }
  async listGameSessions() { const items = await this.prisma.gameSession.findMany({ orderBy: { createdAt: 'desc' }, take: 100, include: { user: { select: { id: true, username: true, phone: true } }, provider: { select: { id: true, name: true, code: true } }, game: { select: { id: true, name: true, providerGameCode: true, category: true } }, transfers: { select: { id: true, type: true, status: true, amount: true, currency: true, createdAt: true }, take: 10, orderBy: { createdAt: 'desc' } } } }); return { items, summary: { total: items.length, launched: items.filter((item) => item.status === 'LAUNCHED').length, failed: items.filter((item) => item.status === 'FAILED').length, active: items.filter((item) => item.status === 'ACTIVE').length } }; }
  async getGameSession(id: string) { const item = await this.prisma.gameSession.findUnique({ where: { id }, include: { user: { select: { id: true, username: true, phone: true } }, provider: { select: { id: true, name: true, code: true } }, game: { select: { id: true, name: true, providerGameCode: true, category: true } }, transfers: { orderBy: { createdAt: 'desc' } } } }); if (!item) throw new NotFoundException('Game session not found'); return item; }
  async listProviderEndpoints(providerId: string) { await this.assertProvider(providerId); const items = await this.prisma.gameProviderEndpoint.findMany({ where: { providerId }, orderBy: { type: 'asc' } }); return { items }; }
  async createProviderEndpoint(providerId: string, input: NormalizedGameProviderEndpointInput, actor: AdminActor, meta: RequestMeta) { await this.assertProvider(providerId); try { const item = await this.prisma.gameProviderEndpoint.create({ data: { providerId, ...input } as Prisma.GameProviderEndpointUncheckedCreateInput }); await this.audit(actor, 'game_provider_endpoint.create', item.id, null, this.safeJson(item), meta); return item; } catch (error) { this.handleProviderWriteError(error, 'Endpoint type already exists for this provider'); } }
  async updateProviderEndpoint(providerId: string, endpointId: string, input: Partial<NormalizedGameProviderEndpointInput>, actor: AdminActor, meta: RequestMeta) { await this.assertProvider(providerId); const current = await this.prisma.gameProviderEndpoint.findFirst({ where: { id: endpointId, providerId } }); if (!current) throw new NotFoundException('Game provider endpoint not found'); try { const item = await this.prisma.gameProviderEndpoint.update({ where: { id: endpointId }, data: input as Prisma.GameProviderEndpointUpdateInput }); await this.audit(actor, 'game_provider_endpoint.update', item.id, this.safeJson(current), this.safeJson(item), meta); return item; } catch (error) { this.handleProviderWriteError(error, 'Endpoint type already exists for this provider'); } }
  async listProviderCredentials(providerId: string) { await this.assertProvider(providerId); const items = await this.prisma.gameProviderCredential.findMany({ where: { providerId }, orderBy: { type: 'asc' }, select: this.credentialSelect() }); return { items }; }
  async createProviderCredential(providerId: string, input: NormalizedGameProviderCredentialInput, actor: AdminActor, meta: RequestMeta) { await this.assertProvider(providerId); try { const item = await this.prisma.gameProviderCredential.create({ data: { providerId, type: input.type, encryptedValue: this.encryptSecret(input.value), maskedValue: this.maskSecret(input.value), isEnabled: input.isEnabled, rotatedAt: new Date() } as Prisma.GameProviderCredentialUncheckedCreateInput, select: this.credentialSelect() }); await this.audit(actor, 'game_provider_credential.create', item.id, null, this.safeJson(item), meta); return item; } catch (error) { this.handleProviderWriteError(error, 'Credential type already exists for this provider'); } }
  async updateProviderCredential(providerId: string, credentialId: string, input: NormalizedGameProviderCredentialUpdate, actor: AdminActor, meta: RequestMeta) { await this.assertProvider(providerId); const current = await this.prisma.gameProviderCredential.findFirst({ where: { id: credentialId, providerId }, select: this.credentialSelect() }); if (!current) throw new NotFoundException('Game provider credential not found'); const data: Prisma.GameProviderCredentialUpdateInput = {}; if (input.type !== undefined) data.type = input.type as any; if (input.isEnabled !== undefined) data.isEnabled = input.isEnabled; if (input.value !== undefined) { data.encryptedValue = this.encryptSecret(input.value); data.maskedValue = this.maskSecret(input.value); data.rotatedAt = new Date(); } try { const item = await this.prisma.gameProviderCredential.update({ where: { id: credentialId }, data, select: this.credentialSelect() }); await this.audit(actor, 'game_provider_credential.update', item.id, this.safeJson(current), this.safeJson(item), meta); return item; } catch (error) { this.handleProviderWriteError(error, 'Credential type already exists for this provider'); } }
  async healthCheckProvider(providerId: string, actor: AdminActor, meta: RequestMeta) { const provider = await this.prisma.gameProvider.findUnique({ where: { id: providerId }, include: { endpoints: { where: { isEnabled: true }, orderBy: { type: 'asc' } }, credentials: { where: { isEnabled: true }, orderBy: { type: 'asc' }, select: this.credentialSecretSelect() } } }); if (!provider) throw new NotFoundException('Game provider not found'); const readiness = this.providerReadiness(provider); const adapter = this.adapterRegistry.getAdapter(provider.code); const context = this.buildAdapterContext(provider); await this.markCredentialUse(provider.id); const result = await adapter.healthCheck(context); const response = { ok: result.ok, providerCode: result.providerCode, requestId: result.requestId, payload: result.payload, errorCode: result.errorCode, errorMessage: result.errorMessage, readiness, adapterRegistered: true, checkedAt: new Date().toISOString() }; await this.audit(actor, 'game_provider.health_check', provider.id, null, this.safeJson({ ok: result.ok, payload: result.payload, errorCode: result.errorCode, readiness }), meta); return response; }
  private async upsertProviderGame(providerId: string, payload: ProviderGamePayload) { if (!payload.providerGameCode || !payload.name || !payload.category) return 'skipped'; const existing = await this.prisma.game.findUnique({ where: { providerId_providerGameCode: { providerId, providerGameCode: payload.providerGameCode } }, select: { id: true } }); const game = await this.prisma.game.upsert({ where: { providerId_providerGameCode: { providerId, providerGameCode: payload.providerGameCode } }, update: { name: payload.name, category: payload.category, status: payload.status, metadata: { rawPayload: payload.rawPayload ?? null } }, create: { providerId, providerGameCode: payload.providerGameCode, name: payload.name, category: payload.category, status: payload.status, metadata: { rawPayload: payload.rawPayload ?? null } } }); await this.upsertSyncedMedia(game.id, providerId, payload); return existing ? 'updated' : 'created'; }
  private async upsertSyncedMedia(gameId: string, providerId: string, payload: ProviderGamePayload) { const media = [{ type: 'COVER', url: payload.imageUrl }, { type: 'ICON', url: payload.iconUrl }, { type: 'BANNER', url: payload.bannerUrl }].filter((item): item is { type: 'COVER' | 'ICON' | 'BANNER'; url: string } => Boolean(item.url)); for (const item of media) { const current = await this.prisma.gameMedia.findFirst({ where: { gameId, type: item.type, isOverride: false }, select: { id: true } }); const data = { gameId, providerId, type: item.type, sourceUrl: item.url, cachedUrl: item.url, status: 'READY' as const, isOverride: false, metadata: { source: 'adapter-sync' } }; if (current) await this.prisma.gameMedia.update({ where: { id: current.id }, data }); else await this.prisma.gameMedia.create({ data }); } }
  private async assertProvider(providerId: string) { const provider = await this.prisma.gameProvider.findUnique({ where: { id: providerId }, select: { id: true } }); if (!provider) throw new NotFoundException('Game provider not found'); return provider; }
  private gameData(input: Partial<NormalizedGameInput>) { const data: Record<string, unknown> = {}; if (input.providerId !== undefined) data.providerId = input.providerId; if (input.providerGameCode !== undefined) data.providerGameCode = input.providerGameCode; if (input.name !== undefined) data.name = input.name; if (input.category !== undefined) data.category = input.category; if (input.status !== undefined) data.status = input.status; if (input.sortOrder !== undefined) data.sortOrder = input.sortOrder; if (input.isFeatured !== undefined) data.isFeatured = input.isFeatured; if (input.isNew !== undefined) data.isNew = input.isNew; if (input.isPopular !== undefined) data.isPopular = input.isPopular; if (input.metadata !== undefined) data.metadata = input.metadata as Prisma.InputJsonValue; return data; }
  private mediaData(input: Partial<NormalizedGameMediaInput>) { const data: Record<string, unknown> = {}; if (input.type !== undefined) data.type = input.type; if (input.sourceUrl !== undefined) data.sourceUrl = input.sourceUrl; if (input.cachedUrl !== undefined) data.cachedUrl = input.cachedUrl; if (input.status !== undefined) data.status = input.status; if (input.isOverride !== undefined) data.isOverride = input.isOverride; if (input.metadata !== undefined) data.metadata = input.metadata as Prisma.InputJsonValue; return data; }
  private buildAdapterContext(provider: { code: string; walletMode: GameProviderWalletMode; currency: string; endpoints: Array<{ type: GameProviderEndpointType; url: string; timeoutMs: number }>; credentials: Array<{ type: string; maskedValue: string; encryptedValue?: string }> }): ProviderAdapterContext { const endpointMap = provider.endpoints.reduce<Partial<Record<GameProviderEndpointType, string>>>((result, endpoint) => { result[endpoint.type] = endpoint.url; return result; }, {}); const credentialMap = provider.credentials.reduce<Record<string, string>>((result, credential) => { result[credential.type] = credential.encryptedValue ? this.decryptSecret(credential.encryptedValue) : credential.maskedValue; return result; }, {}); return { providerCode: provider.code, baseUrl: endpointMap.HEALTH_CHECK ?? endpointMap.LAUNCH ?? '', walletMode: provider.walletMode, currency: provider.currency, timeoutMs: Math.max(...provider.endpoints.map((endpoint) => endpoint.timeoutMs), 10000), endpointMap, credentialMap }; }
  private providerReadiness(provider: { status: string; code: string; endpoints?: Array<{ type: GameProviderEndpointType; isEnabled: boolean }>; credentials?: Array<{ type: string; isEnabled: boolean }> }) { const endpointSet = new Set((provider.endpoints ?? []).filter((item) => item.isEnabled).map((item) => item.type)); const credentialSet = new Set((provider.credentials ?? []).filter((item) => item.isEnabled).map((item) => item.type)); const checks = [{ key: 'adapter_registered', label: 'Adapter registered', ok: this.adapterRegistry.hasAdapter(provider.code) }, { key: 'provider_active', label: 'Provider active', ok: provider.status === 'ACTIVE' }, { key: 'launch_endpoint', label: 'LAUNCH endpoint enabled', ok: endpointSet.has('LAUNCH') }, { key: 'balance_endpoint', label: 'BALANCE endpoint enabled', ok: endpointSet.has('BALANCE') }, { key: 'transfer_endpoints', label: 'TRANSFER_IN and TRANSFER_OUT enabled', ok: endpointSet.has('TRANSFER_IN') && endpointSet.has('TRANSFER_OUT') }, { key: 'api_key', label: 'API_KEY credential enabled', ok: credentialSet.has('API_KEY') }, { key: 'webhook_secret', label: 'WEBHOOK_SECRET credential enabled', ok: credentialSet.has('WEBHOOK_SECRET') }]; return { checks, ready: checks.every((item) => item.ok), passed: checks.filter((item) => item.ok).length, total: checks.length }; }
  private credentialSelect() { return { id: true, providerId: true, type: true, maskedValue: true, isEnabled: true, rotatedAt: true, lastUsedAt: true, createdAt: true, updatedAt: true } as const; }
  private credentialSecretSelect() { return { id: true, providerId: true, type: true, maskedValue: true, encryptedValue: true, isEnabled: true, rotatedAt: true, lastUsedAt: true, createdAt: true, updatedAt: true } as const; }
  private encryptSecret(value: string) { const key = this.credentialKey(); const iv = randomBytes(12); const cipher = createCipheriv('aes-256-gcm', key, iv); const encrypted = Buffer.concat([cipher.update(value, 'utf8'), cipher.final()]); const tag = cipher.getAuthTag(); return `aes-256-gcm:${iv.toString('base64')}:${tag.toString('base64')}:${encrypted.toString('base64')}`; }
  private decryptSecret(value: string) { const [, ivRaw, tagRaw, encryptedRaw] = value.split(':'); if (!ivRaw || !tagRaw || !encryptedRaw) return value; const decipher = createDecipheriv('aes-256-gcm', this.credentialKey(), Buffer.from(ivRaw, 'base64')); decipher.setAuthTag(Buffer.from(tagRaw, 'base64')); return Buffer.concat([decipher.update(Buffer.from(encryptedRaw, 'base64')), decipher.final()]).toString('utf8'); }
  private credentialKey() { const keySource = this.configService.get<string>('GAME_CREDENTIAL_SECRET') ?? this.configService.get<string>('JWT_ACCESS_KEY') ?? 'local_game_credential_key'; return createHash('sha256').update(keySource).digest(); }
  private maskSecret(value: string) { if (value.length <= 8) return `${value.slice(0, 1)}••••${value.slice(-1)}`; return `${value.slice(0, 4)}••••${value.slice(-4)}`; }
  private async markCredentialUse(providerId: string) { await this.prisma.gameProviderCredential.updateMany({ where: { providerId, isEnabled: true }, data: { lastUsedAt: new Date() } }); }
  private async audit(actor: AdminActor, action: string, targetId: string, oldData: Prisma.InputJsonValue | null, newData: Prisma.InputJsonValue | null, meta: RequestMeta) { await this.prisma.adminAuditLog.create({ data: { adminUserId: actor.id, action, module: 'game-platform', targetId, oldData: oldData ?? Prisma.JsonNull, newData: newData ?? Prisma.JsonNull, ipAddress: meta.ipAddress, userAgent: meta.userAgent } }); }
  private safeJson(value: unknown) { return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue; }
  private handleProviderWriteError(error: unknown, message: string): never { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') throw new ConflictException(message); throw error; }
}
