import SettingsSectionPage from '../settings-section-page';

const FEATURES_DEFAULTS = {
  registration_enabled: true,
  login_enabled: true,
  profile_enabled: true,
  kyc_enabled: true,
  deposit_enabled: true,
  withdraw_enabled: true,
  promotion_enabled: true,
  bonus_enabled: true,
  event_enabled: true,
  news_enabled: true,
  vip_enabled: true,
  referral_enabled: true,
  coupon_enabled: true,
  affiliate_enabled: true,
  game_lobby_enabled: true,
  provider_enabled: true,
  support_enabled: true,
  notification_enabled: true,
  articles_enabled: true,
  hero_enabled: true,
  announcement_enabled: true,
  tournament_enabled: true,
  jackpot_enabled: true,
  leaderboard_enabled: true,
  mini_games_enabled: true,
  popular_games_enabled: true,
  online_games_enabled: true,
  live_games_enabled: true,
  classic_games_enabled: true,
  usage_guide_enabled: true,
  tournament_title: 'TOURNAMENT เข้าร่วมชิงความเป็นที่ 1',
  tournament_summary: 'ร่วมสนุกกับกิจกรรม Tournament',
  tournament_image_url: '/assets/asset-pc/images/ZAB1/tournament/4a7df032-03f5-4999-ba59-f38d12c13761.png',
  jackpot_title: 'JACKPOTS',
  jackpot_amount: '194,428,645',
  jackpot_subtitle: 'Epic of the day',
  jackpot_image_url: '/assets/asset-pc/images/FEZX/highlight/1725948738165-4cb4f1ec-44ed-4b21-99ed-398fbb6d7b25.gif',
  leaderboard_title: 'Leaderboard',
  featured_title: 'เกมไฮไลท์',
  popular_title: 'Top 10 Popular Games',
  online_title: 'Most Online Now',
  live_title: 'Live Now!!',
  classic_title: 'Classic Games',
  guide_title: 'คู่มือการใช้งาน',
  navigation_items_json: '[]',
  tournament_items_json: '[]',
  leaderboard_items_json: '[]',
  mini_games_json: '[]',
};

export default function FeaturesSettingsPage() {
  return (
    <SettingsSectionPage
      group="features"
      title="การเปิดปิดฟีเจอร์"
      description="ควบคุมความสามารถ เนื้อหา และส่วนประกอบหน้า Member จากจุดเดียว ทั้ง Desktop และ Mobile โดยไม่ต้อง deploy ใหม่"
      preview="features"
      risk="sensitive"
      defaults={FEATURES_DEFAULTS}
      fields={[
        { key: 'registration_enabled', label: 'เปิดสมัครสมาชิก', type: 'checkbox', section: 'บัญชีสมาชิก', helper: 'ปิดแล้วผู้ใช้ใหม่จะสมัครไม่ได้' },
        { key: 'login_enabled', label: 'เปิดเข้าสู่ระบบ', type: 'checkbox', section: 'บัญชีสมาชิก', helper: 'ปิดแล้วสมาชิกจะเข้าสู่ระบบไม่ได้' },
        { key: 'profile_enabled', label: 'เปิดโปรไฟล์', type: 'checkbox', section: 'บัญชีสมาชิก' },
        { key: 'kyc_enabled', label: 'เปิด KYC และบัญชีธนาคาร', type: 'checkbox', section: 'บัญชีสมาชิก' },
        { key: 'deposit_enabled', label: 'เปิดฝากเงิน', type: 'checkbox', section: 'ธุรกรรม', helper: 'กระทบการสร้างรายการฝากใหม่ทันที' },
        { key: 'withdraw_enabled', label: 'เปิดถอนเงิน', type: 'checkbox', section: 'ธุรกรรม', helper: 'กระทบการสร้างรายการถอนใหม่ทันที' },
        { key: 'promotion_enabled', label: 'เปิดโปรโมชัน', type: 'checkbox', section: 'การตลาดและรางวัล' },
        { key: 'bonus_enabled', label: 'เปิดโบนัส', type: 'checkbox', section: 'การตลาดและรางวัล' },
        { key: 'event_enabled', label: 'เปิดกิจกรรม', type: 'checkbox', section: 'การตลาดและรางวัล' },
        { key: 'news_enabled', label: 'เปิดข่าวสาร', type: 'checkbox', section: 'การตลาดและรางวัล', helper: 'ควบคุม Quick Action และรายการข่าวทั้ง Desktop/Mobile' },
        { key: 'vip_enabled', label: 'เปิด VIP', type: 'checkbox', section: 'การตลาดและรางวัล' },
        { key: 'referral_enabled', label: 'เปิด Referral', type: 'checkbox', section: 'การตลาดและรางวัล' },
        { key: 'coupon_enabled', label: 'เปิด Coupon', type: 'checkbox', section: 'การตลาดและรางวัล' },
        { key: 'affiliate_enabled', label: 'เปิดตัวแทน / Affiliate', type: 'checkbox', section: 'การตลาดและรางวัล' },
        { key: 'game_lobby_enabled', label: 'เปิด Game Lobby', type: 'checkbox', section: 'เกมและ Provider' },
        { key: 'provider_enabled', label: 'เปิด Provider', type: 'checkbox', section: 'เกมและ Provider' },
        { key: 'support_enabled', label: 'เปิดศูนย์ช่วยเหลือ', type: 'checkbox', section: 'บริการสมาชิก' },
        { key: 'notification_enabled', label: 'เปิดศูนย์แจ้งเตือน', type: 'checkbox', section: 'บริการสมาชิก' },
        { key: 'articles_enabled', label: 'เปิด SEO / Articles', type: 'checkbox', section: 'เนื้อหา' },
        { key: 'hero_enabled', label: 'แสดง Hero Banner', type: 'checkbox', section: 'หน้าแรก Desktop และ Mobile', helper: 'ซ่อนหรือแสดง Hero พร้อมกันทั้งสองหน้าจอ' },
        { key: 'announcement_enabled', label: 'แสดงแถบประกาศ', type: 'checkbox', section: 'หน้าแรก Desktop และ Mobile', helper: 'ใช้ประกาศระบบจาก Content Center ชุดเดียวกัน' },
        { key: 'tournament_enabled', label: 'แสดง Tournament', type: 'checkbox', section: 'หน้าแรก Desktop และ Mobile' },
        { key: 'jackpot_enabled', label: 'แสดง Jackpot', type: 'checkbox', section: 'หน้าแรก Desktop และ Mobile' },
        { key: 'leaderboard_enabled', label: 'แสดง Leaderboard', type: 'checkbox', section: 'หน้าแรก Desktop และ Mobile' },
        { key: 'mini_games_enabled', label: 'แสดง Mini Game', type: 'checkbox', section: 'หน้าแรก Desktop และ Mobile' },
        { key: 'popular_games_enabled', label: 'แสดงเกมยอดนิยม', type: 'checkbox', section: 'หน้าแรก Desktop และ Mobile' },
        { key: 'online_games_enabled', label: 'แสดงเกมที่กำลังออนไลน์', type: 'checkbox', section: 'หน้าแรก Desktop และ Mobile' },
        { key: 'live_games_enabled', label: 'แสดง Live Now', type: 'checkbox', section: 'หน้าแรก Desktop และ Mobile' },
        { key: 'classic_games_enabled', label: 'แสดง Classic Games', type: 'checkbox', section: 'หน้าแรก Desktop และ Mobile' },
        { key: 'usage_guide_enabled', label: 'แสดงคู่มือการใช้งาน', type: 'checkbox', section: 'หน้าแรก Desktop และ Mobile' },
        { key: 'tournament_title', label: 'ชื่อ Tournament', type: 'text', section: 'ข้อความหน้าแรกกลาง', maxLength: 160 },
        { key: 'tournament_summary', label: 'คำอธิบาย Tournament', type: 'text', section: 'ข้อความหน้าแรกกลาง', maxLength: 240 },
        { key: 'tournament_image_url', label: 'รูป Tournament', type: 'text', section: 'ข้อความหน้าแรกกลาง', asset: true, helper: 'รองรับ URL หรือ path ภายในเว็บ' },
        { key: 'jackpot_title', label: 'ชื่อ Jackpot', type: 'text', section: 'ข้อความหน้าแรกกลาง', maxLength: 80 },
        { key: 'jackpot_amount', label: 'ตัวเลข Jackpot', type: 'text', section: 'ข้อความหน้าแรกกลาง', maxLength: 40 },
        { key: 'jackpot_subtitle', label: 'คำอธิบาย Jackpot', type: 'text', section: 'ข้อความหน้าแรกกลาง', maxLength: 120 },
        { key: 'jackpot_image_url', label: 'รูป Jackpot', type: 'text', section: 'ข้อความหน้าแรกกลาง', asset: true, helper: 'รองรับ URL หรือ path ภายในเว็บ' },
        { key: 'leaderboard_title', label: 'ชื่อ Leaderboard', type: 'text', section: 'ข้อความหน้าแรกกลาง', maxLength: 80 },
        { key: 'featured_title', label: 'ชื่อส่วนเกมไฮไลท์', type: 'text', section: 'ชื่อ Section เกมกลาง', maxLength: 80 },
        { key: 'popular_title', label: 'ชื่อส่วนเกมยอดนิยม', type: 'text', section: 'ชื่อ Section เกมกลาง', maxLength: 80 },
        { key: 'online_title', label: 'ชื่อส่วนเกมออนไลน์', type: 'text', section: 'ชื่อ Section เกมกลาง', maxLength: 80 },
        { key: 'live_title', label: 'ชื่อส่วน Live', type: 'text', section: 'ชื่อ Section เกมกลาง', maxLength: 80 },
        { key: 'classic_title', label: 'ชื่อส่วน Classic', type: 'text', section: 'ชื่อ Section เกมกลาง', maxLength: 80 },
        { key: 'guide_title', label: 'ชื่อส่วนคู่มือ', type: 'text', section: 'ชื่อ Section เกมกลาง', maxLength: 80 },
        {
          key: 'navigation_items_json',
          label: 'เมนู Desktop/Mobile (JSON)',
          type: 'textarea',
          section: 'ข้อมูล Runtime ขั้นสูง',
          helper: 'กำหนด id, labelTh, labelEn, href, iconKey, desktop, mobile, feature, requiresAuth และ order; ใช้ [] เพื่อใช้ค่าเริ่มต้น',
        },
        {
          key: 'tournament_items_json',
          label: 'Tournament และอันดับ (JSON)',
          type: 'textarea',
          section: 'ข้อมูล Runtime ขั้นสูง',
          helper: 'แต่ละรายการรองรับ id, title, status, href, startsAt, endsAt และ players[{rank,name,score,stats}]',
        },
        {
          key: 'leaderboard_items_json',
          label: 'Leaderboard (JSON)',
          type: 'textarea',
          section: 'ข้อมูล Runtime ขั้นสูง',
          helper: 'รูปแบบ [{rank,name,user,amount,image}] และจะแสดงชุดเดียวกันทั้ง Desktop/Mobile',
        },
        {
          key: 'mini_games_json',
          label: 'Mini Games (JSON)',
          type: 'textarea',
          section: 'ข้อมูล Runtime ขั้นสูง',
          helper: 'รูปแบบ [{id,title,subtitle,href,image,enabled}] และใช้ข้อมูลเดียวกันทุกหน้าจอ',
        },
      ]}
    />
  );
}
