'use client';

import { useEffect, useMemo, useState } from 'react';
import { adminApiFetch } from '../../admin-api';
import { AdminBadge, AdminButton, AdminCard, AdminEmpty, AdminGrid, AdminLinkButton, AdminMetric, AdminMetricGrid, AdminNotice, AdminPage, AdminRow, AdminStack } from '../_components/admin-ui';

type Provider = { id: string; name: string; code: string; status: string; walletMode?: string; metadata?: any };
type Panel = { provider?: Provider; status?: string; checks?: Array<{ key: string; ok: boolean }>; flags?: Record<string, boolean> };
type BadgeTone = 'success' | 'warning' | 'danger' | 'neutral';
type NoticeTone = 'neutral' | 'success' | 'warning' | 'danger' | 'brand';
type HumanStatus = { label: string; tone: BadgeTone; helper: string };
type NextAction = { title: string; description: string; label: string; tone: BadgeTone };

export default function SimpleGameSettingsPage() {
  const [providers, setProviders] = useState<Provider[]>([]);
  const [providerId, setProviderId] = useState('');
  const [panel, setPanel] = useState<Panel | null>(null);
  const [message, setMessage] = useState('กำลังโหลดค่ายเกม...');
  const [messageTone, setMessageTone] = useState<NoticeTone>('neutral');
  const [loading, setLoading] = useState(false);
  useEffect(() => { loadProviders(); }, []);
  useEffect(() => { if (providerId) loadPanel(providerId); }, [providerId]);
  const selected = useMemo(() => providers.find((item) => item.id === providerId), [providers, providerId]);
  const human = humanProviderStatus(selected, panel);
  function showMessage(nextMessage: string, tone: NoticeTone = 'neutral') { setMessage(nextMessage); setMessageTone(tone); }
  async function loadProviders() { setLoading(true); showMessage('กำลังโหลดค่ายเกม...'); const res = await adminApiFetch('/admin/game-providers'); const data = await res.json().catch(() => null); setLoading(false); if (!res.ok) { showMessage(data?.message ?? 'โหลดค่ายเกมไม่สำเร็จ', 'danger'); return; } const rows = data.items ?? []; setProviders(rows); setProviderId(rows[0]?.id ?? ''); showMessage(rows.length ? '' : 'ยังไม่มีค่ายเกม', rows.length ? 'neutral' : 'warning'); }
  async function loadPanel(id = providerId) { if (!id) return; const res = await adminApiFetch(`/admin/game-providers/${id}/risk-panel`); const data = await res.json().catch(() => null); if (res.ok) { setPanel(data); return; } showMessage(data?.message ?? 'โหลดสถานะค่ายไม่สำเร็จ', 'danger'); }
  async function testHealth() { if (!providerId) { showMessage('เลือกค่ายก่อนทดสอบ', 'warning'); return; } setLoading(true); showMessage('กำลังทดสอบค่าย...'); const res = await adminApiFetch(`/admin/game-providers/${providerId}/health-check`, { method: 'POST' }); const data = await res.json().catch(() => null); setLoading(false); showMessage(res.ok && data?.ok !== false ? 'ทดสอบค่ายสำเร็จ' : data?.message ?? data?.errorMessage ?? 'ทดสอบค่ายไม่สำเร็จ', res.ok && data?.ok !== false ? 'success' : 'danger'); await loadPanel(); }
  async function openSafeGates() { if (!providerId) { showMessage('เลือกค่ายก่อนเปิดใช้งานพื้นฐาน', 'warning'); return; } setLoading(true); showMessage('กำลังเปิดโหมดใช้งานพื้นฐาน...'); const res = await adminApiFetch(`/admin/game-providers/${providerId}/gates`, { method: 'PATCH', body: JSON.stringify({ launchEnabled: true, transferEnabled: true, walletSyncEnabled: true, realMoneyEnabled: false, webhookSettlementEnabled: false }) }); const data = await res.json().catch(() => null); setLoading(false); showMessage(res.ok ? 'เปิดโหมดใช้งานพื้นฐานแล้ว ยังไม่เปิดเงินจริง/เว็บฮุคเงินจริง' : data?.message ?? 'เปิดโหมดไม่สำเร็จ', res.ok ? 'success' : 'danger'); await loadPanel(); }
  return <AdminPage eyebrow="ตั้งค่าง่าย" title="ตั้งค่าค่ายเกม" description="หน้าเดียวสำหรับดูว่าค่ายพร้อมไหม ต้องทำอะไรต่อ และไปหน้าขั้นสูงเฉพาะตอนจำเป็น" actions={<><AdminButton onClick={testHealth} disabled={loading || !providerId}>ทดสอบค่าย</AdminButton><AdminButton tone="secondary" onClick={openSafeGates} disabled={loading || !providerId}>เปิดใช้งานพื้นฐาน</AdminButton></>}>
    {message && <AdminNotice tone={messageTone}>{message}</AdminNotice>}
    <AdminMetricGrid><AdminMetric title="สถานะค่าย" value={human.label} helper={human.helper} /><AdminMetric title="ค่ายที่เลือก" value={selected?.name ?? '-'} helper={selected?.code ?? 'ยังไม่ได้เลือก'} /><AdminMetric title="เปิดเกม" value={yesNo(panel?.flags?.launchEnabled)} helper="ให้สมาชิกเข้าเกม" /><AdminMetric title="โยกเงิน" value={yesNo(panel?.flags?.walletSyncEnabled)} helper="เชื่อมวอเลตกับเกม" /></AdminMetricGrid>
    <AdminCard title="เลือกค่าย"><select value={providerId} onChange={(event) => setProviderId(event.target.value)} style={inputStyle}>{providers.map((provider) => <option key={provider.id} value={provider.id}>{provider.name} ({provider.code})</option>)}</select></AdminCard>
    <AdminGrid>
      <AdminCard title="ต้องทำอะไรต่อ" description="แปลจากสถานะเทคนิคให้เป็นงานที่คนทำงานจริงเข้าใจ"><AdminStack>{nextActions(selected, panel).map((item) => <AdminRow key={item.title}><div><strong>{item.title}</strong><p style={mutedStyle}>{item.description}</p></div><AdminBadge tone={item.tone}>{item.label}</AdminBadge></AdminRow>)}</AdminStack></AdminCard>
      <AdminCard title="ทางลัดที่ใช้บ่อย" description="หน้าอื่นยังอยู่ แต่ไม่ต้องเปิดทุกหน้าให้เวียนหัว"><div style={shortcutGridStyle}><AdminLinkButton href="/provider-setup-wizard">เพิ่มค่ายใหม่</AdminLinkButton><AdminLinkButton href="/provider-credentials">ใส่/เปลี่ยน API Key</AdminLinkButton><AdminLinkButton href="/adapter-test">ทดสอบ API</AdminLinkButton><AdminLinkButton href="/game-transfers">ดูการโยกเงิน</AdminLinkButton><AdminLinkButton href="/reconciliation-center">ตรวจยอดเงิน</AdminLinkButton><AdminLinkButton href="/risk-alerts">ปัญหาที่ต้องดู</AdminLinkButton></div></AdminCard>
      <AdminCard title="สถานะที่ซ่อนรายละเอียดเทคนิค" description="เราใช้คำง่ายแทน status ยาว ๆ เพราะแอดมินไม่ควรต้องแปล enum เพื่อทำงาน"><AdminStack>{(panel?.checks ?? []).map((check) => <AdminRow key={check.key}><span>{checkLabel(check.key)}</span><AdminBadge tone={check.ok ? 'success' : 'warning'}>{check.ok ? 'เรียบร้อย' : 'ต้องทำ'}</AdminBadge></AdminRow>)}{!panel?.checks?.length && <AdminEmpty>ยังไม่มีข้อมูลตรวจค่าย</AdminEmpty>}</AdminStack></AdminCard>
      <AdminCard title="หน้าขั้นสูง" description="ใช้เฉพาะตอน debug หรือเชื่อมค่ายจริง"><div style={shortcutGridStyle}><AdminLinkButton href="/provider-risk">ตรวจละเอียด</AdminLinkButton><AdminLinkButton href="/game-api-settings">ตั้งค่า API แบบเดิม</AdminLinkButton><AdminLinkButton href="/webhook-test">ทดสอบ Webhook</AdminLinkButton><AdminLinkButton href="/webhook-logs">ประวัติ Webhook</AdminLinkButton></div></AdminCard>
    </AdminGrid>
  </AdminPage>;
}
function humanProviderStatus(provider?: Provider, panel?: Panel | null): HumanStatus { if (!provider) return { label: 'ยังไม่มีค่าย', tone: 'neutral', helper: 'เพิ่มค่ายก่อน' }; if (provider.status !== 'ACTIVE') return { label: 'ปิดอยู่', tone: 'neutral', helper: 'ยังไม่เปิดให้ใช้งาน' }; const failed = (panel?.checks ?? []).filter((item) => !item.ok).length; if (failed === 0) return { label: 'พร้อมใช้', tone: 'success', helper: 'ตรวจพื้นฐานครบ' }; if (failed <= 2) return { label: 'ต้องตรวจ', tone: 'warning', helper: `เหลือ ${failed} จุด` }; return { label: 'มีปัญหา', tone: 'danger', helper: `ต้องแก้ ${failed} จุด` }; }
function yesNo(value?: boolean) { return value ? 'เปิด' : 'ปิด'; }
function nextActions(provider?: Provider, panel?: Panel | null): NextAction[] { const checks = new Map((panel?.checks ?? []).map((item) => [item.key, item.ok])); const rows: NextAction[] = []; if (!provider) return [{ title: 'เพิ่มค่ายเกม', description: 'เริ่มจากเพิ่มค่ายด้วย Wizard', label: 'ต้องทำ', tone: 'warning' }]; if (provider.status !== 'ACTIVE') rows.push({ title: 'เปิดค่าย', description: 'ค่ายนี้ยังปิดอยู่ เปิดเมื่อทดสอบผ่านแล้ว', label: 'ต้องตรวจ', tone: 'warning' }); if (checks.get('adapter_registered') === false) rows.push({ title: 'ยังไม่มีตัวเชื่อม API', description: 'ต้องใช้ generic adapter หรือเขียน adapter เฉพาะค่าย', label: 'สำคัญ', tone: 'danger' }); if (checks.get('api_key') === false || checks.get('webhook_secret') === false) rows.push({ title: 'ใส่ API Key / Secret', description: 'ไปหน้าใส่/เปลี่ยน API Key แล้วทดสอบอีกครั้ง', label: 'ต้องทำ', tone: 'warning' }); if (checks.get('launch_endpoint') === false || checks.get('balance_endpoint') === false || checks.get('transfer_in_endpoint') === false || checks.get('transfer_out_endpoint') === false) rows.push({ title: 'ตั้งค่า URL API', description: 'endpoint สำหรับเปิดเกม/เช็กยอด/โยกเงินยังไม่ครบ', label: 'ต้องทำ', tone: 'warning' }); if (rows.length === 0) rows.push({ title: 'พร้อมทดสอบใช้งาน', description: 'ลองเปิดเกม โยกเงินเข้า/ออก แล้วตรวจยอด', label: 'พร้อม', tone: 'success' }); return rows; }
function checkLabel(key: string) { const map: Record<string, string> = { adapter_registered: 'มีตัวเชื่อม API', provider_active: 'ค่ายเปิดใช้งาน', transfer_wallet_mode: 'โหมดโยกเงินถูกต้อง', wallet_sync_enabled: 'เชื่อมวอเลตแล้ว', launch_endpoint: 'URL เปิดเกม', balance_endpoint: 'URL เช็กยอด', transfer_in_endpoint: 'URL โยกเข้าเกม', transfer_out_endpoint: 'URL โยกกลับวอเลต', webhook_endpoint: 'URL รับ Webhook', api_key: 'API Key', webhook_secret: 'Webhook Secret', latest_reconciliation_safe: 'ยอดล่าสุดปลอดภัย', no_unresolved_mismatch: 'ไม่มีปัญหายอดค้าง', real_money_disabled_by_default: 'เงินจริงยังปิดอยู่' }; return map[key] ?? key; }
const inputStyle = { width: '100%', minHeight: 44, borderRadius: 12, border: '1px solid rgba(148,163,184,.22)', background: '#0b1220', color: '#f8fafc', padding: '0 12px', boxSizing: 'border-box' as const, fontSize: 15 };
const shortcutGridStyle = { display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(180px,100%),1fr))', gap: 10 } as const;
const mutedStyle = { margin: 0, color: '#94a3b8', lineHeight: 1.55 } as const;