'use client';

import { useEffect, useState } from 'react';
import { adminApiFetch } from '../../admin-api';
import { AdminBadge, AdminButton, AdminCard, AdminEmpty, AdminLinkButton, AdminMetric, AdminMetricGrid, AdminNotice, AdminPage, AdminRow, AdminStack } from '../_components/admin-ui';

type Provider = { id: string; name: string; code: string; status: string; metadata?: unknown };
type Credential = { id: string; type: string; maskedValue: string; isEnabled: boolean; rotatedAt?: string | null; createdAt: string; updatedAt: string };
type NoticeTone = 'neutral' | 'success' | 'warning' | 'danger' | 'brand';
type SafeTestResult = { provider: string; status: 'SUCCESS' | 'FAILED'; httpStatus: string; latency: string; testedAt: string };
type ProviderEnvironment = 'PRODUCTION' | 'UAT' | 'DEMO';
type EnvironmentFilter = 'ALL' | ProviderEnvironment;

export default function ProviderCredentialsPage() {
  const [providers, setProviders] = useState<Provider[]>([]);
  const [providerId, setProviderId] = useState('');
  const [items, setItems] = useState<Credential[]>([]);
  const [message, setMessage] = useState('กำลังโหลด API Key...');
  const [messageTone, setMessageTone] = useState<NoticeTone>('neutral');
  const [loading, setLoading] = useState(false);
  const [testResult, setTestResult] = useState<SafeTestResult | null>(null);
  const [environmentFilter, setEnvironmentFilter] = useState<EnvironmentFilter>('ALL');
  useEffect(() => { loadProviders(); }, []);
  useEffect(() => { if (providerId) loadCredentials(providerId); }, [providerId]);
  function showMessage(nextMessage: string, tone: NoticeTone = 'neutral') { setMessage(nextMessage); setMessageTone(tone); }
  async function loadProviders() { showMessage('กำลังโหลดค่าย...', 'neutral'); const res = await adminApiFetch('/admin/game-providers'); const data = await res.json().catch(() => null); if (!res.ok) { showMessage('โหลดค่ายเกมไม่สำเร็จ', 'danger'); return; } const rows = data.items ?? []; setProviders(rows); setProviderId(rows[0]?.id ?? ''); showMessage(rows.length ? '' : 'ยังไม่มีค่ายสำหรับตั้งค่า API Key', rows.length ? 'neutral' : 'warning'); }
  async function loadCredentials(id = providerId) { setLoading(true); showMessage('กำลังโหลด API Key...', 'neutral'); const res = await adminApiFetch(`/admin/game-providers/${id}/credentials`); const data = await res.json().catch(() => null); setLoading(false); if (!res.ok) { showMessage('โหลด API Key ไม่สำเร็จ', 'danger'); return; } setItems(data.items ?? []); showMessage(''); }
  async function rotate(item: Credential) { const value = window.prompt(`ค่าใหม่สำหรับ ${credentialLabel(item.type)}`); if (!value) return; if (!window.confirm(`เปลี่ยน ${credentialLabel(item.type)} ใช่ไหม? ค่าเก่าจะถูกแทนที่`)) return; setLoading(true); showMessage(`กำลังเปลี่ยน ${credentialLabel(item.type)}...`, 'neutral'); const res = await adminApiFetch(`/admin/game-providers/${providerId}/credentials/${item.id}`, { method: 'PATCH', body: JSON.stringify({ value, isEnabled: true }) }); await res.json().catch(() => null); setLoading(false); if (!res.ok) { showMessage('เปลี่ยน API Key ไม่สำเร็จ', 'danger'); return; } showMessage(`เปลี่ยน ${credentialLabel(item.type)} แล้ว`, 'success'); await loadCredentials(); }
  async function toggle(item: Credential) { if (item.isEnabled && !window.confirm(`ปิด ${credentialLabel(item.type)} ใช่ไหม? ถ้าค่ายต้องใช้ค่านี้ API อาจใช้งานไม่ได้`)) return; setLoading(true); showMessage(`กำลัง${item.isEnabled ? 'ปิด' : 'เปิดใช้'} ${credentialLabel(item.type)}...`, 'neutral'); const res = await adminApiFetch(`/admin/game-providers/${providerId}/credentials/${item.id}`, { method: 'PATCH', body: JSON.stringify({ isEnabled: !item.isEnabled }) }); await res.json().catch(() => null); setLoading(false); if (!res.ok) { showMessage('บันทึกสถานะ API Key ไม่สำเร็จ', 'danger'); return; } showMessage(`${!item.isEnabled ? 'เปิดใช้' : 'ปิด'} ${credentialLabel(item.type)} แล้ว`, item.isEnabled ? 'warning' : 'success'); await loadCredentials(); }
  async function testProvider() { const selected = providers.find((item) => item.id === providerId); if (selected && providerEnvironment(selected) === 'PRODUCTION' && !window.confirm('ทดสอบการเชื่อมต่อ Production ใช่ไหม? ระบบจะตรวจเฉพาะ health check และไม่ทำรายการเงิน')) return; setLoading(true); showMessage('กำลังทดสอบการเชื่อมต่อ...', 'neutral'); const startedAt = performance.now(); const res = await adminApiFetch(`/admin/game-providers/${providerId}/health-check`, { method: 'POST' }); await res.json().catch(() => null); setLoading(false); setTestResult(safeTestResult(res.ok, res.status, performance.now() - startedAt, selected?.name)); showMessage(res.ok ? 'ทดสอบการเชื่อมต่อสำเร็จ' : 'ทดสอบการเชื่อมต่อไม่สำเร็จ', res.ok ? 'success' : 'danger'); }
  function selectEnvironment(next: EnvironmentFilter) { setEnvironmentFilter(next); const selected = providers.find((item) => next === 'ALL' || providerEnvironment(item) === next); const nextProviderId = selected?.id ?? ''; if (nextProviderId !== providerId) { setProviderId(nextProviderId); setItems([]); } setTestResult(null); showMessage(selected ? '' : `ยังไม่มีค่าย${environmentLabel(next)}`, selected ? 'neutral' : 'warning'); }
  const enabled = items.filter((item) => item.isEnabled).length;
  const placeholders = items.filter(isPlaceholder).length;
  const stale = items.filter((item) => item.rotatedAt && Date.now() - new Date(item.rotatedAt).getTime() > 90 * 24 * 60 * 60 * 1000).length;
  const visibleProviders = providers.filter((item) => environmentFilter === 'ALL' || providerEnvironment(item) === environmentFilter);
  const selectedProvider = providers.find((item) => item.id === providerId);
  return <AdminPage eyebrow="ตั้งค่าค่ายเกม" title="API Key / Secret" description="เก็บค่าแบบปิดบัง แยกตามสภาพแวดล้อม" actions={<><AdminButton onClick={testProvider} disabled={loading || !providerId}>ทดสอบการเชื่อมต่อ</AdminButton><AdminLinkButton href="/simple-game-settings">กลับตั้งค่าง่าย</AdminLinkButton></>}>
    {message && <AdminNotice tone={messageTone}>{message}</AdminNotice>}
    <AdminMetricGrid><AdminMetric title="ทั้งหมด" value={String(items.length)} helper="ค่าที่บันทึกไว้" /><AdminMetric title="เปิดใช้" value={String(enabled)} helper="ระบบนำไปใช้ได้" /><AdminMetric title="ปิดอยู่" value={String(items.length - enabled)} helper="ระบบไม่ใช้" /><AdminMetric title="ข้อมูลเก่า" value={String(placeholders)} helper="ต้องแก้ก่อนใช้จริง" tone={placeholders ? 'danger' : 'neutral'} /><AdminMetric title="นานเกิน 90 วัน" value={String(stale)} helper="ควรตรวจ" tone={stale ? 'warning' : 'neutral'} /></AdminMetricGrid>
    <AdminCard title="สภาพแวดล้อม" description="Production ใช้จริง, UAT ทดสอบ, Demo จำลอง"><div style={actionRowStyle} role="group" aria-label="เลือกสภาพแวดล้อม">{(['ALL', 'PRODUCTION', 'UAT', 'DEMO'] as const).map((environment) => <AdminButton key={environment} tone={environmentFilter === environment ? 'primary' : 'secondary'} onClick={() => selectEnvironment(environment)}>{environmentLabel(environment)}</AdminButton>)}</div></AdminCard>
    <AdminCard title="เลือกค่าย" action={selectedProvider ? <AdminBadge tone={environmentTone(providerEnvironment(selectedProvider))}>{environmentLabel(providerEnvironment(selectedProvider))}</AdminBadge> : undefined}><select value={providerId} onChange={(event) => setProviderId(event.target.value)} style={inputStyle} disabled={!visibleProviders.length}>{visibleProviders.map((provider) => <option key={provider.id} value={provider.id}>{provider.name} ({provider.code}) · {environmentLabel(providerEnvironment(provider))}</option>)}</select>{!visibleProviders.length && <AdminEmpty>ยังไม่มีค่าย{environmentLabel(environmentFilter)}</AdminEmpty>}</AdminCard>
    {placeholders > 0 && <AdminNotice tone="danger">พบ credential เก่าที่เป็น placeholder ให้เปลี่ยนก่อนใช้จริง</AdminNotice>}
    {stale > 0 && <AdminNotice tone="warning">มีค่าที่ไม่ได้เปลี่ยนเกิน 90 วันแล้ว ควรตรวจรอบเปลี่ยนคีย์เพื่อความปลอดภัย</AdminNotice>}
    <AdminStack>{items.map((item) => <AdminCard key={item.id} title={credentialLabel(item.type)} description={`เปลี่ยนล่าสุด: ${item.rotatedAt ? new Date(item.rotatedAt).toLocaleString('th-TH') : '-'}`}><AdminRow><div><strong>{item.maskedValue}</strong><p style={mutedStyle}>อัปเดต {new Date(item.updatedAt).toLocaleString('th-TH')}</p></div><div style={actionRowStyle}><AdminBadge tone={item.isEnabled ? 'success' : 'danger'}>{item.isEnabled ? 'เปิดใช้' : 'ปิดอยู่'}</AdminBadge>{isPlaceholder(item) && <AdminBadge tone="warning">ตัวอย่าง</AdminBadge>}</div></AdminRow><div style={actionRowStyle}><AdminButton onClick={() => rotate(item)} disabled={loading}>เปลี่ยนค่า</AdminButton><AdminButton tone="secondary" onClick={() => toggle(item)} disabled={loading}>{item.isEnabled ? 'ปิด' : 'เปิดใช้'}</AdminButton></div></AdminCard>)}{!loading && items.length === 0 && <AdminEmpty>ยังไม่มี API Key / Secret</AdminEmpty>}</AdminStack>
    {testResult && <AdminCard title="ผลทดสอบ API" description="แสดงเฉพาะข้อมูลที่ปลอดภัย ไม่แสดง secret หรือ payload จากค่าย"><AdminStack><AdminRow><strong>ค่าย</strong><span>{testResult.provider}</span></AdminRow><AdminRow><strong>สถานะ</strong><AdminBadge tone={testResult.status === 'SUCCESS' ? 'success' : 'danger'}>{testResult.status === 'SUCCESS' ? 'สำเร็จ' : 'ไม่สำเร็จ'}</AdminBadge></AdminRow><AdminRow><strong>HTTP status</strong><span>{testResult.httpStatus}</span></AdminRow><AdminRow><strong>Latency</strong><span>{testResult.latency}</span></AdminRow><AdminRow><strong>ทดสอบเมื่อ</strong><span>{testResult.testedAt}</span></AdminRow></AdminStack></AdminCard>}
  </AdminPage>;
}
function providerEnvironment(provider: Provider): ProviderEnvironment { const metadata = provider.metadata && typeof provider.metadata === 'object' ? provider.metadata as Record<string, unknown> : {}; const declared = typeof metadata.environment === 'string' ? metadata.environment.toUpperCase() : ''; if (declared === 'PRODUCTION' || declared === 'UAT' || declared === 'DEMO') return declared; if (provider.code.toLowerCase().endsWith('-uat')) return 'UAT'; if (provider.code.toLowerCase().startsWith('demo-') || provider.code.toLowerCase().startsWith('simulator-')) return 'DEMO'; return 'PRODUCTION'; }
function environmentLabel(environment: EnvironmentFilter) { const labels: Record<EnvironmentFilter, string> = { ALL: 'ทั้งหมด', PRODUCTION: 'Production', UAT: 'UAT', DEMO: 'Demo' }; return labels[environment]; }
function environmentTone(environment: ProviderEnvironment) { return environment === 'PRODUCTION' ? 'danger' : environment === 'UAT' ? 'warning' : 'success'; }
function credentialLabel(type: string) { const map: Record<string, string> = { API_KEY: 'API Key', SECRET_KEY: 'Secret Key', MERCHANT_ID: 'Merchant ID', AGENT_ID: 'Agent ID', WEBHOOK_SECRET: 'Webhook Secret', TOKEN: 'Token' }; return map[type] ?? type; }
function isPlaceholder(item: Credential) { return item.maskedValue?.includes('TODO') || item.maskedValue?.includes('placeholder'); }
function safeTestResult(ok: boolean, httpStatus: number, elapsedMs: number, provider?: string): SafeTestResult { return { provider: provider || '-', status: ok ? 'SUCCESS' : 'FAILED', httpStatus: String(httpStatus), latency: `${Math.max(0, Math.round(elapsedMs)).toLocaleString('th-TH')} ms`, testedAt: new Date().toLocaleString('th-TH') }; }
const inputStyle = { width: '100%', minHeight: 44, borderRadius: 12, border: '1px solid rgba(148,163,184,.22)', background: '#0b1220', color: '#f8fafc', padding: '0 12px', boxSizing: 'border-box' as const, fontSize: 15 };
const actionRowStyle = { display: 'flex', gap: 10, flexWrap: 'wrap' as const, alignItems: 'center' as const };
const mutedStyle = { margin: 0, color: '#94a3b8', lineHeight: 1.55 } as const;
