export const API_ERROR_CODES = {
  FINANCE_INVALID_STATE: 'FINANCE_INVALID_STATE',
  FINANCE_IDEMPOTENCY_CONFLICT: 'FINANCE_IDEMPOTENCY_CONFLICT',
  FINANCE_INSUFFICIENT_BALANCE: 'FINANCE_INSUFFICIENT_BALANCE',
  WITHDRAWAL_CLAIM_REQUIRED: 'WITHDRAWAL_CLAIM_REQUIRED',
  WITHDRAWAL_CLAIM_CONFLICT: 'WITHDRAWAL_CLAIM_CONFLICT',
  WITHDRAWAL_PROOF_INVALID: 'WITHDRAWAL_PROOF_INVALID',
  RISK_ALERT_NOT_FOUND: 'RISK_ALERT_NOT_FOUND',
  RISK_ALERT_INVALID_TRANSITION: 'RISK_ALERT_INVALID_TRANSITION',
  RISK_ALERT_SCAN_COOLDOWN: 'RISK_ALERT_SCAN_COOLDOWN',
  PROMOTION_CAMPAIGN_NOT_FOUND: 'PROMOTION_CAMPAIGN_NOT_FOUND',
  PROMOTION_DUPLICATE_CLAIM: 'PROMOTION_DUPLICATE_CLAIM',
  PROMOTION_INVALID_LIFECYCLE: 'PROMOTION_INVALID_LIFECYCLE',
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export type ApiErrorPayload = {
  code: ApiErrorCode;
  message: string;
  details?: Record<string, unknown>;
  requestId?: string;
};
