import type { MemberLocale } from '../../member-locale-provider';

export type GuideTab = 'all' | 'finance' | 'activity' | 'play' | 'affiliate' | 'benefits' | 'trouble';

export type LocalizedGuideText = Readonly<{
  th: string;
  en: string;
}>;

export type GuideItem = Readonly<{
  question: LocalizedGuideText;
  answer: LocalizedGuideText;
}>;

export type GuideGroup = Readonly<{
  id: string;
  tab: Exclude<GuideTab, 'all'>;
  title: LocalizedGuideText;
  items: readonly GuideItem[];
}>;

const text = (th: string, en: string): LocalizedGuideText => ({ th, en });
const item = (questionTh: string, questionEn: string, answerTh: string, answerEn: string): GuideItem => ({
  question: text(questionTh, questionEn),
  answer: text(answerTh, answerEn),
});

export const USAGE_GUIDE_COPY = {
  title: text('แนะนำการใช้งาน', 'Usage Guide'),
  close: text('ปิดหน้าต่าง', 'Close dialog'),
  tabList: text('หมวดแนะนำการใช้งาน', 'Usage guide categories'),
} as const;

export const USAGE_GUIDE_TABS: readonly { id: GuideTab; label: LocalizedGuideText }[] = [
  { id: 'all', label: text('ทั้งหมด', 'All') },
  { id: 'finance', label: text('การฝาก - ถอน', 'Deposit - Withdraw') },
  { id: 'activity', label: text('กิจกรรม', 'Activities') },
  { id: 'play', label: text('การเข้าเล่น', 'How to Play') },
  { id: 'affiliate', label: text('สร้างรายได้เครือข่าย', 'Affiliate Earnings') },
  { id: 'benefits', label: text('สิทธิประโยชน์', 'Benefits') },
  { id: 'trouble', label: text('เกิดปัญหาในการเล่นเกม?', 'Game Issues?') },
] as const;

export const USAGE_GUIDE_GROUPS: readonly GuideGroup[] = [
  {
    id: 'deposit',
    tab: 'finance',
    title: text('การฝากเงิน', 'Deposits'),
    items: [
      item(
        'ฝากเงินแบบ โอนผ่านธนาคาร',
        'Deposit by bank transfer',
        'เลือกเมนูฝากเงิน เลือกธนาคาร ระบุยอด แล้วโอนตามข้อมูลที่ระบบแสดงให้ครบถ้วน',
        'Open Deposit, select a bank, enter the amount, and transfer using the account details shown by the system.',
      ),
      item(
        'ฝากเงินแบบ โอนผ่าน QR Payment',
        'Deposit with QR Payment',
        'เลือก QR Payment ระบุยอด และสแกน QR ภายในเวลาที่ระบบกำหนด',
        'Choose QR Payment, enter the amount, and scan the generated QR code before it expires.',
      ),
      item(
        'ฝากเงินแบบ ฝากจุดทศนิยม',
        'Deposit using a decimal amount',
        'โอนยอดรวมจุดทศนิยมให้ตรงกับยอดที่ระบบสร้าง เพื่อให้ระบบตรวจสอบรายการอัตโนมัติ',
        'Transfer the exact decimal amount generated by the system so the payment can be matched automatically.',
      ),
      item(
        'วิธีการฝากแบบ TrueWallet',
        'Deposit with TrueWallet',
        'เลือกช่องทาง TrueWallet กรอกข้อมูลให้ครบ และทำรายการตามขั้นตอนบนหน้าจอ',
        'Choose TrueWallet, complete the required information, and follow the instructions shown on screen.',
      ),
      item(
        'ยอดไม่เข้าทันที ทำยังไงดี?',
        'What should I do if the balance is delayed?',
        'ตรวจสอบสถานะรายการและหลักฐานการโอน หากเกินเวลาที่แจ้งไว้ให้ติดต่อฝ่ายบริการลูกค้า',
        'Check the transaction status and transfer receipt. Contact customer service if it remains delayed beyond the stated time.',
      ),
    ],
  },
  {
    id: 'withdraw',
    tab: 'finance',
    title: text('การถอนเงิน', 'Withdrawals'),
    items: [
      item(
        'การถอนเงิน',
        'How to withdraw',
        'เลือกบัญชีรับเงิน ระบุยอดถอน ตรวจสอบข้อมูล แล้วกดยืนยันรายการ',
        'Select the receiving account, enter the withdrawal amount, review the details, and confirm the request.',
      ),
    ],
  },
  {
    id: 'promotion',
    tab: 'activity',
    title: text('โปรโมชั่น', 'Promotions'),
    items: [
      item(
        'โปรโมชั่นแนะนำ',
        'Recommended promotions',
        'ตรวจสอบเงื่อนไข ระยะเวลา และยอดทำรายการก่อนรับโปรโมชั่นทุกครั้ง',
        'Review the conditions, validity period, and transaction requirements before claiming a promotion.',
      ),
    ],
  },
  {
    id: 'activities',
    tab: 'activity',
    title: text('รวบรวมทุกกิจกรรม', 'All Activities'),
    items: [
      item('กิจกรรมทายผลคืออะไร?', 'What are prediction activities?', 'กิจกรรมให้สมาชิกเลือกผลการแข่งขันหรือผลรางวัลตามกติกาที่ประกาศในแต่ละรอบ', 'Prediction activities let members choose an outcome under the rules announced for each round.'),
      item('สิ่งที่ต้องทำก่อนทายผล', 'Before submitting a prediction', 'เข้าสู่ระบบ ตรวจสอบกติกา วันปิดรับคำตอบ และสิทธิ์เข้าร่วมก่อนยืนยันคำทาย', 'Sign in and review the rules, closing time, and eligibility before confirming a prediction.'),
      item('เข้าร่วมกิจกรรมทายผลยังไง?', 'How do I join a prediction activity?', 'เปิดหน้ากิจกรรม เลือกรายการที่เปิดรับคำตอบ เลือกผล และกดยืนยัน', 'Open Activities, select an available event, choose an outcome, and confirm.'),
      item('การประกาศรางวัล', 'Prize announcements', 'ผลและรายชื่อผู้ได้รับรางวัลจะแสดงในหน้ากิจกรรมหลังตรวจสอบเสร็จสิ้น', 'Results and winners are published on the activity page after verification is complete.'),
      item('ล็อคอินประจำวัน / ภารกิจ', 'Daily login and missions', 'เข้าสู่ระบบในแต่ละวันและทำภารกิจตามเงื่อนไขเพื่อรับสิทธิ์หรือรางวัล', 'Sign in daily and complete missions according to their conditions to receive benefits or rewards.'),
      item('ขั้นตอน : ทายผลบอล', 'Football prediction steps', 'เลือกคู่แข่งขัน เลือกผลที่คาดการณ์ ตรวจสอบข้อมูล และกดยืนยันก่อนเวลาปิดรับ', 'Select a match and predicted result, review the details, and confirm before entries close.'),
      item('ขั้นตอน : ทายผลมวย', 'Boxing prediction steps', 'เลือกคู่ชกและผลที่คาดการณ์ จากนั้นยืนยันก่อนกิจกรรมปิดรับคำตอบ', 'Select a bout and predicted result, then confirm before the activity closes.'),
      item('ขั้นตอน : ทายผลหวย', 'Lottery prediction steps', 'เลือกรอบ เลือกผลที่คาดการณ์ และยืนยันภายในช่วงเวลาที่กำหนด', 'Select a round and predicted result, then confirm within the stated period.'),
    ],
  },
  {
    id: 'news',
    tab: 'activity',
    title: text('ข่าวสาร', 'News'),
    items: [
      item('ติดตามข่าวสาร', 'Follow the latest news', 'ติดตามประกาศ โปรโมชั่น เกมใหม่ และการปิดปรับปรุงได้จากเมนูข่าวสาร', 'Use the News section to follow announcements, promotions, new games, and maintenance notices.'),
    ],
  },
  {
    id: 'play',
    tab: 'play',
    title: text('การเข้าเล่นคาสิโน', 'How to Play'),
    items: [
      item('เข้าเล่น : คาสิโน', 'Play: Casino', 'เปิดเมนูคาสิโน เลือกค่ายที่ต้องการ แล้วกดเข้าเล่น', 'Open Casino, select a provider, and choose Play.'),
      item('เข้าเล่น : สล็อต', 'Play: Slots', 'เปิดเมนูสล็อต เลือกค่ายหรือใช้ตัวกรอง จากนั้นเลือกเกมที่ต้องการ', 'Open Slots, select a provider or filter, and choose a game.'),
      item('เข้าเล่น : ยิงปลา', 'Play: Fishing', 'เปิดเมนูยิงปลา เลือกเกม แล้วกดเข้าเล่น', 'Open Fishing, select a game, and choose Play.'),
      item('เข้าเล่น : กีฬา', 'Play: Sports', 'เปิดเมนูกีฬา เลือกผู้ให้บริการ แล้วกดเข้าเล่น', 'Open Sports, select a provider, and choose Play.'),
      item('เข้าเล่น : ไพ่', 'Play: Cards', 'เปิดเมนูไพ่ เลือกเกมที่ต้องการ แล้วกดเข้าเล่น', 'Open Cards, select a game, and choose Play.'),
      item('เข้าเล่น : หวย', 'Play: Lottery', 'เปิดเมนูหวย เลือกผู้ให้บริการ แล้วกดเข้าเล่น', 'Open Lottery, select a provider, and choose Play.'),
    ],
  },
  {
    id: 'affiliate',
    tab: 'affiliate',
    title: text('ระบบสร้างรายได้เครือข่าย', 'Affiliate Program'),
    items: [
      item('สร้างรายได้เครือข่าย', 'Earn from your affiliate network', 'เปิดเมนูเครือข่าย คัดลอกลิงก์แนะนำ และตรวจสอบยอดตามเงื่อนไขของระบบ', 'Open the affiliate section, copy your referral link, and review earnings under the program conditions.'),
      item('ถอนรายได้เครือข่าย (แนะนำเพื่อน)', 'Withdraw affiliate earnings', 'ตรวจสอบยอดที่ถอนได้ เลือกบัญชีรับเงิน แล้วส่งคำขอถอนรายได้เครือข่าย', 'Check the available amount, select the receiving account, and submit an affiliate withdrawal request.'),
    ],
  },
  {
    id: 'benefits',
    tab: 'benefits',
    title: text('สิทธิประโยชน์ลูกค้าแต่ละระดับ', 'Member Tier Benefits'),
    items: [
      item('วิธีการตรวจสอบระดับ', 'How to check your tier', 'เปิดโปรไฟล์หรือหน้าสิทธิประโยชน์เพื่อดูระดับปัจจุบันและเงื่อนไขการเลื่อนระดับ', 'Open Profile or Benefits to view your current tier and upgrade requirements.'),
      item('ระดับ Silver', 'Silver tier', 'ดูสิทธิประโยชน์ของระดับ Silver และเงื่อนไขที่หน้าโปรไฟล์สมาชิก', 'View Silver benefits and requirements on the member profile page.'),
      item('ระดับ Gold', 'Gold tier', 'ดูสิทธิประโยชน์ของระดับ Gold และเงื่อนไขที่หน้าโปรไฟล์สมาชิก', 'View Gold benefits and requirements on the member profile page.'),
      item('ระดับ Platinum', 'Platinum tier', 'ดูสิทธิประโยชน์ของระดับ Platinum และเงื่อนไขที่หน้าโปรไฟล์สมาชิก', 'View Platinum benefits and requirements on the member profile page.'),
      item('ระดับ Titanium', 'Titanium tier', 'ดูสิทธิประโยชน์ของระดับ Titanium และเงื่อนไขที่หน้าโปรไฟล์สมาชิก', 'View Titanium benefits and requirements on the member profile page.'),
      item('ระดับ Diamond', 'Diamond tier', 'ดูสิทธิประโยชน์ของระดับ Diamond และเงื่อนไขที่หน้าโปรไฟล์สมาชิก', 'View Diamond benefits and requirements on the member profile page.'),
      item('ระดับ VVIP', 'VVIP tier', 'ดูสิทธิประโยชน์ของระดับ VVIP และเงื่อนไขที่หน้าโปรไฟล์สมาชิก', 'View VVIP benefits and requirements on the member profile page.'),
    ],
  },
  {
    id: 'trouble',
    tab: 'trouble',
    title: text('ปัญหาอินเตอร์เน็ต', 'Connection Issues'),
    items: [
      item('หากเกิดปัญหาในการเล่นเกม เช่น เกมค้าง, ไม่สามารถเข้าเกมได้', 'The game is frozen or cannot be opened', 'ตรวจสอบอินเทอร์เน็ต ปิดเกม แล้วเปิดใหม่ หากยังมีปัญหาให้เก็บภาพหน้าจอและชื่อเกมไว้', 'Check your internet connection and reopen the game. Keep the game name and a screenshot if the problem continues.'),
      item('รีเฟรชหน้าเว็บไซต์', 'Refresh the website', 'บันทึกข้อมูลที่จำเป็นก่อนรีเฟรช จากนั้นโหลดหน้าเว็บใหม่แล้วลองเข้าเกมอีกครั้ง', 'Save any necessary information, refresh the page, and try opening the game again.'),
      item('ติดต่อฝ่ายบริการลูกค้า', 'Contact customer service', 'ส่งชื่อผู้ใช้ ชื่อเกม เวลาที่เกิดปัญหา และภาพหน้าจอให้ฝ่ายบริการลูกค้าตรวจสอบ', 'Send your username, game name, incident time, and a screenshot to customer service.'),
    ],
  },
] as const;

export const HOME_GUIDE_PREVIEW = USAGE_GUIDE_GROUPS[0].items;

export function localizeGuideText(value: LocalizedGuideText, locale: MemberLocale) {
  return value[locale];
}
