-- Commit enum values in their own migration.
-- PostgreSQL requires newly added enum values to be committed before they can be referenced by indexes or data changes.

ALTER TYPE "TopUpRequestStatus" ADD VALUE IF NOT EXISTS 'PENDING_SLIP_REVIEW';
ALTER TYPE "TopUpRequestStatus" ADD VALUE IF NOT EXISTS 'SLIP_APPROVED';
ALTER TYPE "TopUpRequestStatus" ADD VALUE IF NOT EXISTS 'PENDING_CREDIT';
ALTER TYPE "TopUpRequestStatus" ADD VALUE IF NOT EXISTS 'CREDIT_CONFIRMED';
ALTER TYPE "TopUpRequestStatus" ADD VALUE IF NOT EXISTS 'DUPLICATE';
ALTER TYPE "TopUpRequestStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';

ALTER TYPE "WithdrawalRequestStatus" ADD VALUE IF NOT EXISTS 'PENDING_REVIEW';
ALTER TYPE "WithdrawalRequestStatus" ADD VALUE IF NOT EXISTS 'APPROVED_FOR_PAYMENT';
ALTER TYPE "WithdrawalRequestStatus" ADD VALUE IF NOT EXISTS 'PAYMENT_PROOF_UPLOADED';
ALTER TYPE "WithdrawalRequestStatus" ADD VALUE IF NOT EXISTS 'PAYMENT_VERIFIED';

ALTER TYPE "RiskAlertType" ADD VALUE IF NOT EXISTS 'DUPLICATE_DEPOSIT_SLIP';
ALTER TYPE "RiskAlertType" ADD VALUE IF NOT EXISTS 'REPEATED_DUPLICATE_DEPOSIT_SLIP';
