'use client';

import { useEffect, useMemo, useState } from 'react';
import { adminApiFetch } from '../../admin-api';
import { AdminBadge, AdminButton, AdminCard, AdminEmpty, AdminGrid, AdminMetric, AdminMetricGrid, AdminNotice, AdminPage, AdminRow, AdminStack, AdminToolbar } from '../_components/admin-ui';

type LinkedTopup = { id: string; amount: number; currency: string; status: string; method?: string | null; referenceCode?: string | null; createdAt?: string; reviewedAt?: string | null };
type Claim = { id: string; campaignId: string; topupId?: string | null; linkedTopup?: LinkedTopup | null; depositAmount?: number; campaign?: { title?: string; bonusType?: string; bonusValue?: number; minDeposit?: number; maxBonus?: number; turnoverMultiplier?: number }; status: string; rawStatus: string; memberNote?: string; adminNote?: string; settlement?: { enabled?: boolean; reason?: string }; events?: Array<{ by: string; action: string; message?: string; createdAt: string }>; member?: { username?: string | null; phone?: string | null; email?: string | null }; createdAt: string; resolvedAt?: string | null };

export default function PromotionClaimsPage() {
  const [items, setItems] = useState<Claim[]>([]);
  const [status, setStatus] = useState('ALL');
  const [notes, setNotes] = useState<Record<string, string>>({});
  const [message, setMessage] = useState('กำลังโหลดคำขอรับโปร...');
  const [busyId, setBusyId] = useState('');
  useEffect(() => { load(); }, [status]);
  const counts = useMemo(() => ({ pending: items.filter((item) => item.status === 'PENDING').length, reviewing: items.filter((item) => item.status === 'REVIEWING').length, approved: items.filter((item) => item.status === 'APPROVED').length, rejected: items.filter((item) => item.status === 'REJECTED').length }), [items]);
  async function load() { setMessage('กำลังโหลดคำขอรับโปร...'); const params = new URLSearchParams(); if (status !== 'ALL') params.set('status', status); const res = await adminApiFetch(`/admin/promotion-claims?${params.toString()}`); const data = await res.json().catch(() => null); if (!res.ok) { setMessage(data?.message ?? 'โหลดคำขอรับโปรไม่สำเร็จ'); return; } setItems(data.items ?? []); setMessage(''); }
  async function review(id: string, next: 'APPROVED' | 'REJECTED') { const adminNote = (notes[id] ?? '').trim(); if (next === 'REJECTED' && !adminNote) { setMessage('กรุณาใส่เหตุผลก่อนปฏิเสธ'); return; } setBusyId(id); const res = await adminApiFetch(`/admin/promotion-claims/${id}/review`, { method: 'PATCH', body: JSON.stringify({ status: next, adminNote }) }); const data = await res.json().catch(() => null); setBusyId(''); if (!res.ok) { setMessage(data?.message ?? 'ตรวจคำขอไม่สำเร็จ'); return; } setItems((current) => current.map((item) => item.id === id ? data.item : item)); setMessage(next === 'APPROVED' ? 'อนุมัติคำขอแล้ว ยังไม่จ่ายเงินจริงจนกว่า bonus ledger พร้อม' : 'ปฏิเสธคำขอแล้ว'); }
  return <AdminPage eyebrow="Promotion Ops" title="คำขอรับโปร" description="ตรวจคำขอรับโปรของสมาชิก อนุมัติ/ปฏิเสธพร้อม audit แต่ยังไม่ credit เงินโบนัสจริง" actions={<AdminButton onClick={load}>รีเฟรช</AdminButton>}>
    {message && <AdminNotice>{message}</AdminNotice>}
    <AdminMetricGrid><AdminMetric tone={counts.pending > 0 ? 'warning' : 'success'} title="รอตรวจ" value={String(counts.pending)} /><AdminMetric tone="warning" title="กำลังตรวจ" value={String(counts.reviewing)} /><AdminMetric tone="success" title="อนุมัติ" value={String(counts.approved)} /><AdminMetric tone="danger" title="ปฏิเสธ" value={String(counts.rejected)} /></AdminMetricGrid>
    <AdminToolbar><select value={status} onChange={(event) => setStatus(event.target.value)} style={selectStyle}><option value="ALL">ทุกสถานะ</option><option value="OPEN">รอตรวจ</option><option value="REVIEWING">กำลังตรวจ</option><option value="RESOLVED">อนุมัติ</option><option value="DISMISSED">ปฏิเสธ</option></select></AdminToolbar>
    <AdminGrid>{items.map((item) => <AdminCard key={item.id} title={item.campaign?.title ?? item.campaignId} description={`${new Date(item.createdAt).toLocaleString('th-TH')} · ${memberLabel(item)}`} tone={item.status === 'APPROVED' ? 'success' : item.status === 'REJECTED' ? 'danger' : 'warning'}><AdminStack><AdminRow><strong>สถานะ</strong><AdminBadge tone={statusTone(item.status)}>{statusLabel(item.status)}</AdminBadge></AdminRow><AdminRow><strong>สมาชิก</strong><span>{memberLabel(item)}</span></AdminRow><AdminRow><strong>รายการฝากที่ใช้</strong><span>{item.linkedTopup ? `${money(Number(item.linkedTopup.amount))} · ${item.linkedTopup.status} · ${item.linkedTopup.referenceCode ?? item.linkedTopup.id}` : item.topupId ?? '-'}</span></AdminRow><AdminRow><strong>ยอดฝากจริง</strong><span>{money(Number(item.depositAmount ?? item.linkedTopup?.amount ?? 0))}</span></AdminRow><AdminRow><strong>เงื่อนไข</strong><span>โบนัส {bonusLabel(item)} · ฝากขั้นต่ำ {money(item.campaign?.minDeposit ?? 0)} · เทิร์น x{item.campaign?.turnoverMultiplier ?? 0}</span></AdminRow><AdminRow><strong>Settlement</strong><span>{item.settlement?.enabled ? 'เปิด' : `ปิด: ${item.settlement?.reason ?? 'Bonus ledger is not enabled yet'}`}</span></AdminRow>{item.memberNote && <AdminRow><strong>หมายเหตุสมาชิก</strong><span>{item.memberNote}</span></AdminRow>}{item.adminNote && <AdminRow><strong>หมายเหตุแอดมิน</strong><span>{item.adminNote}</span></AdminRow>}<section style={timelineStyle}>{(item.events ?? []).slice(-4).map((event, index) => <div key={index} style={eventStyle}><AdminBadge tone={event.by === 'admin' ? 'success' : 'warning'}>{event.by}</AdminBadge><strong>{event.action}</strong><span>{event.message || '-'}</span><small>{new Date(event.createdAt).toLocaleString('th-TH')}</small></div>)}</section><textarea value={notes[item.id] ?? ''} onChange={(event) => setNotes((current) => ({ ...current, [item.id]: event.target.value }))} placeholder="หมายเหตุแอดมิน" style={textareaStyle} /><div style={actionRowStyle}><AdminButton disabled={busyId === item.id} tone="secondary" onClick={() => review(item.id, 'APPROVED')}>อนุมัติคำขอ</AdminButton><AdminButton disabled={busyId === item.id} tone="danger" onClick={() => review(item.id, 'REJECTED')}>ปฏิเสธ</AdminButton></div></AdminStack></AdminCard>)}{items.length === 0 && <AdminEmpty>ยังไม่มีคำขอรับโปร</AdminEmpty>}</AdminGrid>
  </AdminPage>;
}
function memberLabel(item: Claim) { return item.member?.username ?? item.member?.phone ?? item.member?.email ?? '-'; }
function statusTone(status: string) { if (status === 'APPROVED') return 'success'; if (status === 'REJECTED') return 'danger'; if (status === 'REVIEWING') return 'warning'; return 'neutral'; }
function statusLabel(status: string) { const map: Record<string, string> = { PENDING: 'รอตรวจ', REVIEWING: 'กำลังตรวจ', APPROVED: 'อนุมัติ', REJECTED: 'ปฏิเสธ' }; return map[status] ?? status; }
function bonusLabel(item: Claim) { const value = Number(item.campaign?.bonusValue ?? 0); return item.campaign?.bonusType === 'fixed' ? money(value) : `${value}%`; }
function money(value: number) { return `THB ${Number(value || 0).toLocaleString('th-TH', { minimumFractionDigits: 2 })}`; }
const selectStyle = { minHeight: 44, borderRadius: 12, border: '1px solid rgba(148,163,184,.22)', background: '#0b1220', color: '#f8fafc', padding: '0 12px', minWidth: 180 } as const;
const textareaStyle = { minHeight: 88, borderRadius: 14, border: '1px solid rgba(148,163,184,.22)', background: '#0b1220', color: '#f8fafc', padding: 12, resize: 'vertical' as const, minWidth: 0 };
const actionRowStyle = { display: 'flex', gap: 8, flexWrap: 'wrap' as const };
const timelineStyle = { border: '1px solid rgba(148,163,184,.14)', borderRadius: 16, padding: 12, background: 'rgba(255,255,255,.04)', display: 'grid', gap: 8 } as const;
const eventStyle = { display: 'grid', gap: 4, borderBottom: '1px solid rgba(148,163,184,.10)', paddingBottom: 8 } as const;
