import { createHmac } from 'crypto';
import {
  BalanceInput,
  BalanceOutput,
  BetHistoryInput,
  BetHistoryOutput,
  GameProviderAdapter,
  LaunchGameInput,
  LaunchGameOutput,
  ParsedWebhookEvent,
  ProviderAdapterContext,
  ProviderAdapterResult,
  ProviderGamePayload,
  TransferInput,
  TransferOutput,
  WebhookValidationResult,
} from '../provider-adapter.interface';

function requestId(prefix: string) { return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`; }
function endpoint(context: ProviderAdapterContext, key: keyof ProviderAdapterContext['endpointMap']) { const url = context.endpointMap[key]; if (!url) throw new Error(`${String(key)} endpoint is not configured`); return url; }
function secret(context: ProviderAdapterContext, key: string) { return context.credentialMap[key] ?? ''; }
function sign(context: ProviderAdapterContext, body: unknown, timestamp: string) { const apiSecret = secret(context, 'SECRET_KEY') || secret(context, 'WEBHOOK_SECRET') || secret(context, 'API_KEY'); return createHmac('sha256', apiSecret).update(`${timestamp}.${JSON.stringify(body)}`).digest('hex'); }
function sanitize(value: unknown) { return JSON.parse(JSON.stringify(value, (key, item) => ['apiKey', 'secret', 'signature', 'SECRET_KEY', 'API_KEY', 'WEBHOOK_SECRET'].includes(key) ? '[REDACTED]' : item)); }

export class GenericTransferProviderAdapter implements GameProviderAdapter {
  async healthCheck(context: ProviderAdapterContext): Promise<ProviderAdapterResult<{ status: 'ONLINE' | 'OFFLINE' | 'DEGRADED'; latencyMs?: number }>> {
    const started = Date.now();
    try { const res = await this.post(context, endpoint(context, 'HEALTH_CHECK'), { ping: true }); return { ok: res.ok, providerCode: context.providerCode, requestId: requestId('generic_health'), payload: { status: res.ok ? 'ONLINE' : 'DEGRADED', latencyMs: Date.now() - started }, rawResponse: sanitize(res.body) }; }
    catch (error) { return { ok: false, providerCode: context.providerCode, requestId: requestId('generic_health'), payload: { status: 'OFFLINE', latencyMs: Date.now() - started }, errorCode: 'HEALTH_CHECK_FAILED', errorMessage: error instanceof Error ? error.message : 'Health check failed' }; }
  }
  async launchGame(context: ProviderAdapterContext, input: LaunchGameInput): Promise<ProviderAdapterResult<LaunchGameOutput>> { const body = { userId: input.userId, gameCode: input.gameCode, sessionId: input.sessionId, ipAddress: input.ipAddress, userAgent: input.userAgent, returnUrl: input.returnUrl }; const res = await this.post(context, endpoint(context, 'LAUNCH'), body); if (!res.ok) return this.fail(context, 'generic_launch', 'LAUNCH_FAILED', res); const payload = res.body as any; return { ok: true, providerCode: context.providerCode, requestId: requestId('generic_launch'), payload: { launchUrl: String(payload.launchUrl ?? payload.url ?? ''), providerSessionId: payload.providerSessionId ?? payload.sessionId, expiresAt: payload.expiresAt }, rawRequest: sanitize(body), rawResponse: sanitize(payload) }; }
  async getBalance(context: ProviderAdapterContext, input: BalanceInput): Promise<ProviderAdapterResult<BalanceOutput>> { const res = await this.post(context, endpoint(context, 'BALANCE'), input); if (!res.ok) return this.fail(context, 'generic_balance', 'BALANCE_FAILED', res); const payload = res.body as any; return { ok: true, providerCode: context.providerCode, requestId: requestId('generic_balance'), payload: { balance: String(payload.balance ?? '0.00'), currency: payload.currency ?? context.currency, providerUserId: payload.providerUserId ?? input.providerUserId ?? input.userId }, rawRequest: sanitize(input), rawResponse: sanitize(payload) }; }
  async transferIn(context: ProviderAdapterContext, input: TransferInput): Promise<ProviderAdapterResult<TransferOutput>> { return this.transfer(context, 'TRANSFER_IN', input); }
  async transferOut(context: ProviderAdapterContext, input: TransferInput): Promise<ProviderAdapterResult<TransferOutput>> { return this.transfer(context, 'TRANSFER_OUT', input); }
  async syncGames(context: ProviderAdapterContext): Promise<ProviderAdapterResult<ProviderGamePayload[]>> { const res = await this.post(context, endpoint(context, 'GAME_LIST'), { currency: context.currency }); if (!res.ok) return this.fail(context, 'generic_games', 'GAME_LIST_FAILED', res); const raw = res.body as any; const rows = Array.isArray(raw) ? raw : Array.isArray(raw.items) ? raw.items : Array.isArray(raw.games) ? raw.games : []; return { ok: true, providerCode: context.providerCode, requestId: requestId('generic_games'), payload: rows.map((item: any) => ({ providerGameCode: String(item.providerGameCode ?? item.code ?? item.id), name: String(item.name ?? item.title ?? item.code ?? item.id), category: String(item.category ?? item.type ?? 'slot'), status: item.status === 'INACTIVE' ? 'INACTIVE' : 'ACTIVE', imageUrl: item.imageUrl ?? item.coverUrl, iconUrl: item.iconUrl, bannerUrl: item.bannerUrl, rawPayload: item })), rawResponse: sanitize(raw) }; }
  async getBetHistory(context: ProviderAdapterContext, input: BetHistoryInput): Promise<ProviderAdapterResult<BetHistoryOutput>> { const res = await this.post(context, endpoint(context, 'BET_HISTORY'), input); if (!res.ok) return this.fail(context, 'generic_bets', 'BET_HISTORY_FAILED', res); const raw = res.body as any; return { ok: true, providerCode: context.providerCode, requestId: requestId('generic_bets'), payload: { items: raw.items ?? [], nextCursor: raw.nextCursor }, rawRequest: sanitize(input), rawResponse: sanitize(raw) }; }
  async validateWebhook(context: ProviderAdapterContext, headers: Record<string, string | string[] | undefined>, body: unknown): Promise<WebhookValidationResult> { const headerSig = String(headers['x-provider-signature'] ?? headers['x-signature'] ?? ''); const timestamp = String(headers['x-provider-timestamp'] ?? headers['x-timestamp'] ?? ''); const expected = timestamp ? sign(context, body, timestamp) : ''; const valid = Boolean(headerSig && expected && headerSig === expected); const payload = body && typeof body === 'object' ? body as Record<string, unknown> : {}; return { valid, reason: valid ? undefined : 'Invalid generic webhook signature', idempotencyKey: typeof payload.idempotencyKey === 'string' ? payload.idempotencyKey : undefined }; }
  async parseWebhook(_context: ProviderAdapterContext, body: unknown): Promise<ParsedWebhookEvent[]> { const payload = body && typeof body === 'object' ? body as Record<string, unknown> : {}; return [{ eventType: String(payload.eventType ?? 'generic.webhook'), providerTransactionId: typeof payload.providerTransactionId === 'string' ? payload.providerTransactionId : undefined, roundId: typeof payload.roundId === 'string' ? payload.roundId : undefined, idempotencyKey: typeof payload.idempotencyKey === 'string' ? payload.idempotencyKey : undefined, payload }]; }
  private async transfer(context: ProviderAdapterContext, type: 'TRANSFER_IN' | 'TRANSFER_OUT', input: TransferInput): Promise<ProviderAdapterResult<TransferOutput>> { const res = await this.post(context, endpoint(context, type), input); if (!res.ok) return this.fail(context, `generic_${type.toLowerCase()}`, `${type}_FAILED`, res); const payload = res.body as any; return { ok: true, providerCode: context.providerCode, requestId: requestId(`generic_${type.toLowerCase()}`), payload: { providerTransactionId: String(payload.providerTransactionId ?? payload.transactionId ?? input.idempotencyKey), beforeBalance: payload.beforeBalance, afterBalance: payload.afterBalance }, rawRequest: sanitize(input), rawResponse: sanitize(payload) }; }
  private async post(context: ProviderAdapterContext, url: string, body: unknown) { const timestamp = new Date().toISOString(); const response = await fetch(url, { method: 'POST', headers: { 'content-type': 'application/json', 'x-api-key': secret(context, 'API_KEY'), 'x-merchant-id': secret(context, 'MERCHANT_ID') || secret(context, 'AGENT_ID'), 'x-timestamp': timestamp, 'x-signature': sign(context, body, timestamp) }, body: JSON.stringify(body), signal: AbortSignal.timeout(context.timeoutMs) }); const text = await response.text(); const parsed = text ? JSON.parse(text) : {}; return { ok: response.ok, status: response.status, body: parsed }; }
  private fail<T>(context: ProviderAdapterContext, prefix: string, code: string, res: { status?: number; body?: unknown }): ProviderAdapterResult<T> { return { ok: false, providerCode: context.providerCode, requestId: requestId(prefix), errorCode: code, errorMessage: `Provider responded with ${res.status ?? 'error'}`, rawResponse: sanitize(res.body ?? {}) }; }
}
